### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by chrisvidal** [oc-shopaholic/oc-shopaholic-plugin#111]
Hi
I feel that some features are missing like:
- taxes
- discount / coupon code
- featured products
- featured categories

Are they in the pipeline?

**Comment by lautsevich** [comment]
Hi, Chris.

Yes all of this is on our roadmap. Discount/Coupons/Campaign plugins will be released in the near future. We hope before the end of October.

**Comment by chrisvidal** [comment]
excellent! thanks

**Comment by lautsevich** [comment]
Hi, @chrisvidal!

The plugins were released in October.

- [Campaigns for Shopaholic](https://octobercms.com/plugin/lovata-campaignsshopaholic)
- [Coupons for Shopaholic](https://octobercms.com/plugin/lovata-couponsshopaholic)
- [Discounts for Shopaholic](https://octobercms.com/plugin/lovata-discountsshopaholic)

The taxes we plan to add in Shopaholic core next year (asap).

**Comment by lautsevich** [comment]
Hi, @chrisvidal.

We added tax management in the latest minor release (1.21.0). Looking forward to your feedback!

Could you please provide more information about "featured products" and "featured categories"?

**Comment by lautsevich** [comment]
Closed due to the loss of the @chrisvidal interest.
