### ISSUE TITLE
marketplaces or vendors feature

### ISSUE THREAD

**Issue by ajsaces** [oc-shopaholic/oc-shopaholic-plugin#149]
are you still looking at adding marketplaces or a feature to add vendors ? Seems a bit lacking to make this perfect.

**Comment by kharanenka** [comment]
Yes, we have it in the plans, but for now this is not priority task for us.

**Comment by lautsevich** [comment]
Hi @ajsaces,
Due to a lot of requests for the multi-vendor functionality for Shopaholic we just opened a Github issue #176 for gathering the requirements for this. Don't hesitate to provide your thoughts and experience it this domain.

**Comment by lautsevich** [comment]
Сlosed in favor of task number issue #176. Please, continue conversation there.

@ajsaces, please, vote there for this functionality,
