### ISSUE TITLE
[QUESTION] Regarding importing from 1C:Enterprise XML structure

### ISSUE THREAD

**Issue by roulendz** [oc-shopaholic/oc-shopaholic-plugin#153]
Hello, 
Quick question, 
Are you familiar with *1C: Enterprise* software?
I am asking because I want to make product/grouped product/category/subcategory/price/properties/ product translations etc. importer form *1C: Enterprise* to Shopaholic

It uses XML file format. 

Separately products and separately product prices.
The product can have multiple price groups: low volume price group and wholesale buyers price group.

**1. Does Shopaholic support multiple price groups?**

Here you can check the import file structure. 
https://failiem.lv/u/5bb4dr4f

**2. What do you think of default XML structure?**

**3. Maybe you could suggest how 1C export structure should look so it would be easier to import products to your awesome plugin.**

Any help would be apriciated.

**Comment by roulendz** [comment]
Anyone here?

**Comment by kharanenka** [comment]
Hi @roulendz!
I apologize for your waiting for an answer.
Yes, we did several integrations with 1C: Enterprise in our projects.

1. Shopaholic do not support multiple price groups now. But our priority is to add taxes and multicurrency to plugins, where you plan to add multiple price groups.

2 + 3 We have an idea to add catalog import from XML file with ready-made presets for settings, including for 1C: Enterprise

**Comment by kharanenka** [comment]
Import from 1C added in version 1.22.0+
