### ISSUE TITLE
How to change order status via interface? 

### ISSUE THREAD

**Issue by shustrya** [oc-shopaholic/oc-shopaholic-plugin#155]
The payment system (like Yandex Kassa) can send information about the payment to a special address and if the payment system confirmed the payment, then I want to change the status of the order automatically.

**Comment by kharanenka** [comment]
Do you develop your plugin integration with Yandex Kassa?

**Comment by shustrya** [comment]
So far I have not designed it as a plugin. I just use the information from the order generated in Shopaholic. I pass this information through the YandexKassa API. Everything works, but there is not enough feedback functionality.

**Comment by kharanenka** [comment]
You need to develop response from payment gateway yourself.
You can add routes.php file in your custom plugin and process  response from payment gateway.

**Comment by kharanenka** [comment]
Our partners have released [Yandex.Kassa for Shopaholic](https://octobercms.com/plugin/bizmark-yandexkassashopaholic) plugin.

Plugin is verified and recommended by Shopaholic team.
