### ISSUE TITLE
Event registration / ticketing

### ISSUE THREAD

**Issue by maartenmachiels** [oc-shopaholic/oc-shopaholic-plugin#164]
Hi,

Nice to see that the Shopaholic plugin is growing and becoming more popular. 
I've got two questions that now limit me to make the jump to the Shopaholic plugin:

**Ticket sales**
Some clients of mine sell tickets to events. Registration for multiple people should be possible. Ideally, a customer should be able to fill in a set of details (first name, last name, email...) for each person they buy a ticket for. Also, different types of events would require the entry of different data. For example a specific type of event might be for children, so there needs to be a checkbox that the person who is registering is a legal guardian and agrees to the transfer of private data. Another type of event might be for parents only...

**Subscriptions**
Some other clients of mine rely on annual subscriptions. Their customers would receive a payment link every year to renew their subscription. It would be ideal if subscriptions would auto-renew without interaction from the customer, but I think this is difficult using OmniPay.

Are these thing possible with the Lovata Shopaholic suite? Are these features on the roadmap for Lovata? If not, is it realistic to create such functionality on top of the Lovata plugins?

Thanks in advance for looking into this.

**Comment by justynpride** [comment]
I'm in the same position, and would love to know if it would be on the roadmap, or if anyone has done such changes? Related to this is whether it would ever be possible for a user to login and 'edit' their order and so add and remove products and update payments, or have refunds.

**Comment by kharanenka** [comment]
Orders plugin does not have the ability to change the order items after creation from frontend. Refunds are more dependent from payment gateway. If plugin of integration with payment gateway  supports refunds, then this can be used in your project.

**Comment by lautsevich** [comment]
By the way, @maartenmachiels, the Subscriptions plugin has been released https://octobercms.com/plugin/lovata-subscriptionsshopaholic

**Comment by justynpride** [comment]
@kharanenka That's helpful to know. I think I'll be needing to build from scratch.
