### ISSUE TITLE
path category

### ISSUE THREAD

**Issue by ndql1996** [oc-shopaholic/oc-shopaholic-plugin#173]
I need the category path I can't find it in the document eg 

![Screen Shot 2019-04-16 at 10 49 30](https://user-images.githubusercontent.com/31888297/56180937-a2a89080-6035-11e9-8a5c-65a2676ce6f3.png)

**Comment by kharanenka** [comment]
Hi! Do you mean "slug" field?

**Comment by ndql1996** [comment]
Thank you very much for solving the problem
![slug category](https://user-images.githubusercontent.com/31888297/56187117-e1e1dc00-604b-11e9-9702-d6a0bc43df49.png)
