### ISSUE TITLE
Module price product ?

### ISSUE THREAD

**Issue by ndql1996** [oc-shopaholic/oc-shopaholic-plugin#174]
I could not find the price setting module of the product at the backend. Which plugin is it in?  Shopaholic question

**Comment by kharanenka** [comment]
Hi!
You can set prices by creating offers for products.

http://joxi.ru/KAx3nxXSZvxNQ2

You can set price format in application settings. Go to /backend/system/settings/update/lovata/toolbox/config   -> "Price format" tab

http://joxi.ru/EA4gQW1Uov4Wb2
