### ISSUE TITLE
obOffer.images empty despite images being attached to the offer

### ISSUE THREAD

**Issue by Shrenos** [oc-shopaholic/oc-shopaholic-plugin#177]
[This example](https://github.com/lovata/oc-shopaholic-plugin/wiki/Step-2-Create-Product-Page) only works partially, since images are not detected, even if they are attached to the offer and are automatically pulled to the offer in the backend even after reinstalling the plugin and creating a product that has the same name as the one that has been deleted when the plugin was removed. The array is apparently empty.
I've attached a couple of 750×866 JPEG pictures to the offer, one of them as the preview image, and I'm also using Rainlab Translate plugin which may or may not interfere. I used the code as it was provided in the example, without any alterations.

What could possibly be wrong with the array?

**Comment by kharanenka** [comment]
Hi! Sorry, i can't reproduce your bug.

Do you create active product with active offers?

**Comment by Shrenos** [comment]
Yes. Also, I tried adding the following line to the code `<img src="{{ obOffer.preview_image.getThumb(100, 100) }}">`, and it works. So there's nothing wrong with the preview image. But the `images` array is detected as empty, and the other images are not shown.

**Comment by kharanenka** [comment]
[This example](https://github.com/lovata/oc-shopaholic-plugin/wiki/Step-2-Create-Product-Page) uses first offer from offer list. Do you attach images to first offer of product?
