### ISSUE TITLE
Is it possible to connect Yandex Kassa to this module?

### ISSUE THREAD

**Issue by ilya-trifonov** [oc-shopaholic/oc-shopaholic-plugin#179]
Hey. I want to create a small online store using your plugin. But I had a question with receiving payments in Russia. Can I connect Yandex Kassa to the module?

**Comment by lautsevich** [comment]
Hi. One of our partners will release such plugin before the end of May or in early June.

**Comment by ilya-trifonov** [comment]
This is great news!  I'll wait for it

**Comment by kharanenka** [comment]
Our partners have released [Yandex.Kassa for Shopaholic](https://octobercms.com/plugin/bizmark-yandexkassashopaholic) plugin.

Plugin is verified and recommended by Shopaholic team.
