### ISSUE TITLE
[Properties for Shopaholic] Does the price change when changing the product properties?

### ISSUE THREAD

**Issue by hoangvietan96** [oc-shopaholic/oc-shopaholic-plugin#181]
I have a question.

I'm about to buy this plugin: https://octobercms.com/plugin/lovata-propertiesshopaholic

But I wonder if the price changes when we changing the product properties?

Thank you!

**Comment by kharanenka** [comment]
Hi!
There is no such logic in Properties plugin.

**Comment by hoangvietan96** [comment]
Thank you. Is there any plugin can do this @kharanenka ?
```
the price changes when we changing the product properties
```

**Comment by kharanenka** [comment]
Can you get example?
