### ISSUE TITLE
Delete an item from cart ISSUE

### ISSUE THREAD

**Issue by flodigital** [oc-shopaholic/oc-shopaholic-plugin#187]
Hi,
the number of the items selected in Cart (shown on the right of the top header near shopping-cart icon) is not updating when i delete a product from Shopping Cart until the whole page is reloaded (F5).
This is very confusing behavior of the Cart in Sneakers E-Commerce Theme for Shopaholic
Many thanks for solving this.
Best regards,
Florin

**Comment by kharanenka** [comment]
Fixed in 1.1.3 theme version
