### ISSUE TITLE
Packagist is not updated since 1.21.2

### ISSUE THREAD

**Issue by pikanji** [oc-shopaholic/oc-shopaholic-plugin#188]
The Shopaholic package is not up to date in [Packagist](https://packagist.org/packages/lovata/oc-shopaholic-plugin).
The version on Packagist is 1.21.2, but this repository has 1.22.2 at the moment I'm writing this.
Packagist should automatically updates the version when a new tag is pushed to this GitHub repository, if it is properly configured.
Thanks!

**Comment by pikanji** [comment]
This might be the solution.
https://stackoverflow.com/a/53139763/1646699

**Comment by kharanenka** [comment]
Hi!
We changed vendor for repository from lovata to "oc-shopaholic", so synchronization with  packagist broke. I will fix this in coming days.

**Comment by pikanji** [comment]
Oh, I see. Thanks for quick response!

**Comment by kharanenka** [comment]
Hi! We updated webhooks on github. Packages now have last version of plugins

**Comment by pikanji** [comment]
@kharanenka I confirmed that it is synched now.
Thanks!!
