### ISSUE TITLE
Remote offers are considered in the filter by price and sorting

### ISSUE THREAD

**Issue by ZloyCod** [oc-shopaholic/oc-shopaholic-plugin#190]
Remote offers are considered in the filter by price and sorting. 

After deleting an offer in the admin panel, its price is not deleted in the related prices table. In the database table prices no column deleted_at. 

If you apply a price filter or sort, the result will be incorrect. Since the prices in the prices table remain and are taken into account in all filters.

Screenshot table prices - https://yadi.sk/i/kM8XR0IRYwrKMA
Screenshot incorrect filter result - https://yadi.sk/i/BnOucf2HP2Y6GQ

**Comment by kharanenka** [comment]
Fixed in version:
Filters for Shopaholic 1.6.1
Shopaholic 1.22.4
