### ISSUE TITLE
Change image path upload button to media library button

### ISSUE THREAD

**Issue by qroft** [oc-shopaholic/oc-shopaholic-plugin#191]
When i add an image to a product, is it possible to use the media library instead of the upload function?

I like all of my images to be categorized inside folders and if i am correct atm the preview image is uploaded into the public folder, but i would love to be able to select the image from my media library,

Anyone figured out if this is possible?

**Comment by qroft** [comment]
Please allow me to add another 2 cents to this subject.
For the last years i tried out nearly every open source ecommerce solution out there.
The current solution with shopaholic is also the one used for many years in WooCommerce - and the uers hated it. If you only have 10 or 30 products then having your images in one folder might be fine. But as soon as you add more to it, then it because a problem.

That's why i cam up with this idea. If i would know better programming i would try to help but Laravel programming is out of my range :D

**Comment by kharanenka** [comment]
Hi! We chose this way of downloading files for several reasons:

1. Files are downloaded to server with random name. Site manager shouldn't monitor file names. Often managers ignore recommendations. Load files with same name. Load files with incorrect names (for example: "product photo 1.png" - file name contains spaces).
2. If you delete file in backend, then file is automatically deleted on server. You don't need to clean server of garbage.
3. You can set "alt" and "title" attributes for images. This is good for SEO.
4. You can resize images using getThumb () method of file object without installing additional plugins.

**Comment by qroft** [comment]
Ok got it, but...
To 1: you can automate this to rename files. If you look at WooCommerce, Prestashop and some of the other ecommerce solutions, you will see that the mass takes care not only about renaming the file but also putting it into a more or less correct dimension.

To 2: That is correct. But if i have thousands of files in one folder some day, i will also have to check wich one is from shopaholic and wich one not. In this case i would recommend that you add a prefix to each generated image like "shop_"

To 3: i am not saying that you have to add the files manually. At the end the DB stores a link to a file or a filename, not more. So the SEO optimization works for any solution IMHO.

4. Definitely, that is right and good like that to avoid ppl upload their 4000x3000 images into their shop and then argue that the website with OctoberCMS is soooo slow.

Thanks, but i am a folder-orga-nerd. I have my system more organized than my whole life. I have folders for folders for folders.
So at the moment, having not the option to choose the file from a folder structure that i prefer, is definietly a reason for me to not go with shopaholic.

But thanks for the project and i wish the whole team all the best!
Greetings from this corner of the planet.
