### ISSUE TITLE
Is it possible to access Cart.getTotalPrice() from partial, php tab?

### ISSUE THREAD

**Issue by gcsomesz** [oc-shopaholic/oc-shopaholic-plugin#192]
When i try get the total price in php tab, i get an error: Class 'Cart' not found.
The cart component already added to the partial. 

`function onStart()
{
    $total_price = Cart::getTotalPrice();
    $this->page["totalprice"] = Currency::format($total_price, ['format' => 'short']);
}`

**Comment by kharanenka** [comment]
Hi! 
You can get access to components with using $this variable:
```
function onStart() {
   $total_price = $this->Cart::getTotalPrice();
 }
```

**Comment by gcsomesz** [comment]
Thank you for help, but i get a sytax error:
Class name must be a valid object or a string

**Comment by kharanenka** [comment]
1. getTotalPrice() is not static method.
Try next code:
function onStart() {
   $total_price = $this->Cart->getTotalPrice();
 }

2. Did you attach Cart component to layout/page?

**Comment by gcsomesz** [comment]
Oh, my fault!
Forgot to add all layout,but and now working fine! 
Thank you!
