### ISSUE TITLE
Unable to get payment data in PaymentGateway::preparePurchaseData

### ISSUE THREAD

**Issue by pikanji** [oc-shopaholic/oc-shopaholic-plugin#194]
Currently I'm developing a payment plugin for Shopaholic, but unable to get user input for payment through payment gateway interface.

### Expected Behavior
In the implementation of `\Lovata\OrdersShopaholic\Classes\Helper\AbstractPaymentGateway::preparePurchaseData` method, `payment_data` is provided via Order object.
Moreover, after Order object is created by `\Lovata\OrdersShopaholic\Classes\Processor\OrderProcessor::create` through `\Lovata\OrdersShopaholic\Components\MakeOrder::create`, `payment_data` field of the Order object is filled.

### Actual Behavior
`payment_data` field in Order model is empty after Order object is created with user's input data.

My payment gateway class implements `\Lovata\OrdersShopaholic\Classes\Helper\AbstractPaymentGateway::preparePurchaseData`, and `payment_data` from user's input is necessary to prepare for payment execution.
At the point when this method is invoked in `AbstractPaymentGateway::purchase`, the Order object is already available with user's input, but `payment_data`.

**Comment by kharanenka** [comment]
Hi! Does your PR completely solve your issue?
Plugin will be updated soon. Thanks for your contribution.

**Comment by pikanji** [comment]
@kharanenka Thanks!
I confirmed it's working!
