### ISSUE TITLE
Support for Combinations? (Suggestion)

### ISSUE THREAD

**Issue by CamiloManrique** [oc-shopaholic/oc-shopaholic-plugin#197]
First of all I would like to say congratulations on making a great plugin. The backend and the code looks very nice and organized. I was wondering if you have plans for suporting product combinations. Let me give an example:

- I could have a set of combinations called White, Black, Red and Blue
-I could have another set of combinations called S, M, L, XL
- Then I have a Sweater product.

I could be able to assign combinations to a product, so for example I could have a red S sweater, blue M sweater and so on. The idea would be avoiding creating a whole new product to create a variation  of the same product, for example creating a Red Sweater product and a Blue Sweater product, like in the demo store. I noticed that the demo store indeed has clothing size variations for the same product, and checking the backend I can see that each product has a Trade Offer for each size, and that allows you to also have different quantities for each one, but I'm not sure if that is the best way to handle it.

**Comment by kharanenka** [comment]
Hi! Thanks for your feedback!

You can set structure of your catalog at your convenience. You can create "Sweater" product. Offers for "Sweater" product can be sweaters of various sizes and colors. Offers will have 2 properties: color and size. On product page, we will need to make choice on two properties.

We are preparing to release [new documentation](http://shopaholic.one/docs#/catalog-structure/catalog-structure). It already has section on catalog design. I recommend that you look at this section. 

P.S. For seo it will be useful if you make products of different colors as separate products (related products).
