### ISSUE TITLE
Missing files and Jquery problem

### ISSUE THREAD

**Issue by Exodon** [oc-shopaholic/oc-shopaholic-plugin#199]
Hi
I just bought the theme "sneakers E-commerce" for october cms but during a fresh installation I´m having several problems like this: 

**1. Error:** Cannot read config file: /Applications/MAMP/htdocs/projectname/.local.eslintrc
**2. Error:** ENOENT: no such file or directory, open /Applications/MAMP/htdocs/projectname/.stylelintrc'
**3. Several npm packages missing from the package-lock.json, all the packages are related with ES Lint.**
 - Error: Failed to load plugin 'promise' declared in '--config': Cannot find module 'eslint-plugin-promise'
- Error: Failed to load plugin 'standard' declared in '--config': Cannot find module 'eslint-plugin-standard'

**4. Several errors related with : The keyword 'import' is reserved** 
 ```
ERROR in ./themes/lovata-shopaholic-sneakers/partials/article/news-simple-slider/news-simple-slider.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Applications/MAMP/htdocs/duendedidgeridoo/themes/lovata-shopaholic-sneakers/partials/article/news-simple-slider/news-simple-slider.js
  1:1  error  Parsing error: The keyword 'import' is reserved

✖ 1 problem (1 error, 0 warnings)
```

The point 1 and 2 I solved putting the files missing, however I think should come originally when we buy this theme, because we don´t know what kind of settings have been used to code ( Css, Scss or JS )

the point 3 I solved add the missing the npm packages but I think you guys should update the npm packages.

To conclude I´m stuck and I can´t continue working and I have a project to deliver :(. 
Can someone help please.

Regards
Ricardo

**Comment by kharanenka** [comment]
Hi! 

We created a [issue](https://github.com/octobercms/october/issues/4382) on OctoberCMS earlier. Bug is that marketplace deletes files (.eslintrc, .stylelintrc). These files are in original zip archive, which we download to marketplace. We added .octoberinclude file, but that still doesn't work.

Please send your email address or send message to a.khoronenko@lovata.com. I will send you archive with full build folder containing all necessary files for assets building .

**Comment by Exodon** [comment]
thanks for the quick reply. Just sent you an email.

**Comment by Exodon** [comment]
After the new update on theme folder everything looks correct. Feel free to close the ticket.
Thanks for the support.

**Comment by lautsevich** [comment]
You're welcome!
