### ISSUE TITLE
[Question] About number of categories nesting levels 

### ISSUE THREAD

**Issue by kordima** [oc-shopaholic/oc-shopaholic-plugin#200]
Only 2 category levels are supported in demo themes.
In page url used :category and :main_category.
If you make more than 2 levels, then there are problems with URL of the product or a list of categories.  How to describe a URL at large (>2) and different (2-5) levels of nesting?

**Comment by kharanenka** [comment]
Hi! Demo theme supports only 2 levels catalog. You can change this if you modify URL of catalog page.

If you need to be able to set "wildcard" parameter for catalog page, then you need to make custom modifications. Plugins do not have support of "wildcard" parameters now.

You will need to add custom component to handle "wildcard" parameter. You will need to add classes/methods that will generate URL for catalog page and product page with support of "wildcard" parameter.

**Comment by kordima** [comment]
Thank you!
