### ISSUE TITLE
Missing Plugin...but which one ?

### ISSUE THREAD

**Issue by Exodon** [oc-shopaholic/oc-shopaholic-plugin#201]
Hi Shopaholic Team

I´m trying to run the theme "Sneakers Shop" and I downloaded all the necessary plugins you list in the website. However I´m having this error : 

```
We're sorry, but an unhandled error occurred. Please see the details below.

Class name is not registered for the component "ArticleList". Check the component plugin.
/Applications/MAMP/htdocs/duendedidgeridoo/modules/cms/Classes/ComponentManager.php line 200

* @return ComponentBase The component object.
     */
    public function makeComponent($name, $cmsObject = null, $properties = [])
    {
        $className = $this->resolve($name);
        if (!$className) {
            throw new SystemException(sprintf(
                'Class name is not registered for the component "%s". Check the component plugin.',
                $name
            ));
        }
  
        if (!class_exists($className)) {
```

I think this is related with this part of the code, located in the files : news-list.html, index.htm and news-page.html: 

```
[ArticleList]
sorting = "publish|desc"

[ArticleCategoryList]
```
I would like to suggest you put in the readme file all the necessary plugins and their links. This way is more easy to solve this kind of problems.

Thank you

**Comment by kharanenka** [comment]
Hi! You need to install [Lovata.GoodNews](https://octobercms.com/plugin/lovata-goodnews) plugin. If you do not use articles block on your project, then you can remove components from pages.

**Comment by Exodon** [comment]
Tks... Is working

**Comment by johrclaessens** [comment]
I had the same problem today. It would be a good idea to add this plugin to the required plugins on the octoberCMS Website.

**Comment by lautsevich** [comment]
@johrclaessens, thx! We'll do it soon.

**Comment by daftspunk** [comment]
Confirmed this plugin is missing from the "Sneakers" theme requirements
