### ISSUE TITLE
importing csv - categories 

### ISSUE THREAD

**Issue by johnnywo** [oc-shopaholic/oc-shopaholic-plugin#202]
hmmm ... import of CSV file works as expected, but not for the categories column - this remains empty after import.
What Value should appear in the CSV file - the Name of the Category (as string) or the ID of the Category or .. ?
I did not manage to get it work - any advice welcome! Thank you!

**Comment by kharanenka** [comment]
Hi! 
You need to set external category ID. For example:
Your category is "Phones" with ID = 10 and external ID = 33442
You need to set 33442 in categories column for product import file

**Comment by johnnywo** [comment]
Wow! that was quick and this is my solution! It works!
Thanks for your support - and thanks for this great plugin, which I will use for an adapted relaunch of a customer site.

**Comment by lautsevich** [comment]
@johnnywo enjoy! ;)
