### ISSUE TITLE
Cart::onAdd not creating new position

### ISSUE THREAD

**Issue by Cambrai1** [oc-shopaholic/oc-shopaholic-plugin#204]
Hi there, whenever im using Cart::onAdd to create a new position in the cart, no position is created. However, a new cart is created when no cart is already tied to that user id... any help would be greatly appreciated.

**Comment by Cambrai1** [comment]
I have just checked, the Cart::onUpdate does not work either

**Comment by kharanenka** [comment]
Hi! Please, send your js code with ajax request.

**Comment by Cambrai1** [comment]
$("#idForm").submit(function(e) {

    e.preventDefault(); //Prevent actual form submission
    
var data = {
    'cart': [
        {'offer_id': 190, 'quantity': 2, 'property': {'double_cheese': true}},
    ]
};

//Send ajax request and update cart items
$.request('Cart::onAdd', {
    'data': data,
    'update': {'cart-items': '.cart-item-wrapper'}
});
});

I've tried multiple different forms of the code including that found in the bootstrap demo theme

**Comment by Cambrai1** [comment]
Nevermind, it was an error on my part (was not calling the ajax function correctly). thank you for your help though!
