### ISSUE TITLE
Currency / Pricing display conflicts

### ISSUE THREAD

**Issue by Komak57** [oc-shopaholic/oc-shopaholic-plugin#205]
Having some difficulty locating certain features of the Product Card Price management. There doesn't seem to be a specific setting for Currency Format, meaning all items are int(price)+currency. product-card.htm:22 seems to hold the key to fixing the location of the currency format, but I'm having a much harder time trying to find the decimal price to replace the integer value. Am I missing something, or was this designed around a currency that doesn't deal in decimals?

**Comment by kharanenka** [comment]
Hi!  You can set price format in Backend -> Settings -> Application settings -> "Price format" tab

See more info in [new docs](http://shopaholic.one/docs#/modules/prices/home)

**Comment by Komak57** [comment]
Was a lot of digging to find that information. Might I recommend adding an actual price format setting in the Shopaholic config, EG "$1,234.56" / "1234.56£" and so on? Could make it considerably more user friendly. Either way, question solved, thank you.

**Comment by kharanenka** [comment]
We are preparing to release updated documentation. Everything will be described in detail there. Something is already available [here](http://shopaholic.one).

**Comment by Bulmer** [comment]
I can't find any details on how to put the dollar ($) symbol before the price in that documentation. If its not there, can you please explain how to edit the appropriate file?

**Comment by kharanenka** [comment]
You can try code:
```php
{{ obOffer.currency }}{{ obOffer.price }}
```

**Comment by Bulmer** [comment]
Thanks @kharanenka . I'm not familiar with the layout of Octobercms yet. Where would the file be for that change?

**Comment by kharanenka** [comment]
It depends on theme you are using. Our plugins do not have templates. Therefore, this place is determined only by source code of your theme.
