### ISSUE TITLE
Cart::onRemove not removing item from cart

### ISSUE THREAD

**Issue by Cambrai1** [oc-shopaholic/oc-shopaholic-plugin#206]
Im trying to remove items from the cart as explained above.

my relevant code is: 

                
                $("#removecart-{{obOffer.id}}").on('click', function() { //Button is calling
                console.log("removed"); //Test to confirm function run
                var dataRemove = {
                    'cart': [{{obOffer.id}}] //checked in inspector and is assigned
                };
                
                //Send ajax request and update cart items
                $.request('Cart::onRemove', {
                    'data': dataRemove
                });});

any help would be greatly appreciated.

**Comment by kharanenka** [comment]
Hi! 

Your code looks correctly. Please, check that AJAX request is being sent and that request has correct data.

**Comment by Cambrai1** [comment]
The data being passed in is just a single integer (for example obOffer.id = 1 so 'cart' : 1.
The ajax form should be sending as i have done the same with Cart::onAdd and Cart::onUpdate and both of them work.

**Comment by Cambrai1** [comment]
I looked into the code in the Cart.php Component and it seems its expecting input for a type and offer in the onRemove function?

 $sType = Input::get('type', 'offer');

yet the documentation on orders for shopaholic plugin only have the 'cart' data array being passed through the ajax request? could this be the problem? if so what style input does type and offer need to be?

**Comment by kharanenka** [comment]
"type" field is optional. You can send offer ID in "cart" array or you can send cart position ID  in "cart" array with type value = "position"

**Comment by Cambrai1** [comment]
So any idea on what i need to change to enable the remove function?

**Comment by kharanenka** [comment]
Please, check offer ID in cart position table in database and your offer id in request. Did you fill properties for cart position?

**Comment by Cambrai1** [comment]
I've sorted a fix: it only supports a remove for one item at a time but that works for my needs.

AJAX:
                $("#removecart-{{obOffer.id}}").on('click', function() { //Prevent actual form submission
                console.log("removed");
                var dataRemove = {
                    'cart': {{obOffer.id}}
                };
                
                //Send ajax request and update cart items
                $.request('Cart::onRemove', {
                    'data': dataRemove
                });});

Cart::onRemove():

    public function onRemove()
    {
        $arRequestData = Input::get('cart');
        $obActiveShippingType = $this->getActiveShippingTypeFromRequest();
        if (!empty($obActiveShippingType) && $obActiveShippingType->isNotEmpty()) {
            CartProcessor::instance()->setActiveShippingType($obActiveShippingType);
        }

        $sType = Input::get('type', 'offer');

        CartProcessor::instance()->remove($arRequestData);
        Result::setData(CartProcessor::instance()->getCartData());

        return Result::get();
    }

CartProcessor:

    public function remove($arRequestData)
    {

        $obCartPositionList = CartPosition::getByCart($this->obCart->id)->where('item_id','=', $arRequestData)->first();
        $obCartPositionList->forceDelete();

        $this->updateCartData();

        return $this->prepareSuccessResponse();
    }

Kind of a dirty fix but it works!

**Comment by kharanenka** [comment]
This fix will freeze Orders plugin from updates. It is not right.

**Comment by kharanenka** [comment]
Did you fill properties in cart position object?

**Comment by Cambrai1** [comment]
properties being : ? 'cart' : [ { 'propertyName' : propertyValue } ] ?
for example 'cart' : [ { 'offer_id' : 190 } ]

**Comment by kharanenka** [comment]
For example: 

```javascript
//Prepare object with offers
var data = {
    'cart': [
        {'offer_id': 2, 'quantity': 4, 'property': {'double_cheese': true}},
        {'offer_id': 5, 'quantity': 1, 'property': {'double_cheese': false}},
        {'offer_id': 10, 'quantity': 1, 'property': {'double_cheese': true}}
    ],
    'shipping_type_id': 4
};

//Send ajax request and update cart items
$.request('Cart::onAdd', {
    'data': data,
    'update': {'cart-items': '.cart-item-wrapper'}
});

```

**Comment by kharanenka** [comment]
Can you revert plugin code and check plugins/lovata/ordersshopaholic/classes/processor/AbstractCartPositionProcessor.php class, findPosition() method?

**Comment by Cambrai1** [comment]
Plugin code has been reverted, AbstractCartPositionProcessor.php remove function reads:     /**
     * Remove position from current cart
     * @param int    $iPositionID
     * @param string $sType
     * @return void
     * @throws \Exception
     */
    public function remove($iPositionID, $sType = 'offer')
    {
        if (empty($iPositionID)) {
            return;
        }

        if ($sType == 'position') {
            $this->arPositionData = [
                'id'        => $iPositionID,
                'item_type' => static::MODEL_CLASS,
            ];
        } else {
            $this->arPositionData = [
                'item_id'   => $iPositionID,
                'item_type' => static::MODEL_CLASS,
            ];
        }

        $this->findPosition();
        if (empty($this->obCartPosition)) {
            return;
        }

        $this->obCartPosition->delete();
    }

**Comment by Cambrai1** [comment]
find position method: protected function findPosition()
    {
        $iPositionID = array_get($this->arPositionData, 'id');

        $iItemID = array_get($this->arPositionData, 'item_id');
        $sItemType = array_get($this->arPositionData, 'item_type');

        if (!empty($iPositionID)) {
            $this->obCartPosition = CartPosition::withTrashed()->getByCart($this->obCart->id)->getByItemType($sItemType)->find($iPositionID);

            return;
        }

        //Get item property
        $arItemProperty = (array) array_get($this->arPositionData, 'property');

        //Get cart position list by item_id and item_type
        $obCartPositionList = CartPosition::withTrashed()->getByCart($this->obCart->id)->getByItemType($sItemType)->getByItemID($iItemID)->get();
        if ($obCartPositionList->isEmpty()) {
            return;
        }

        /** @var CartPosition $obCartPosition */
        foreach ($obCartPositionList as $obCartPosition) {
            $arCartPositionProperty = (array) $obCartPosition->property;
            $bCheck = (empty($arItemProperty) && empty($arCartPositionProperty))
                || (!array_diff($arItemProperty, $arCartPositionProperty) && !array_diff($arCartPositionProperty, $arItemProperty));
            if ($bCheck) {
                $this->obCartPosition = $obCartPosition;
                break;
            }
        }
    }

**Comment by Cambrai1** [comment]
$.request('Cart::onRemove', {
        data: {
            'cart': [offer_id]
        },
        update: {
            'cart/cart_info': '._cart_info_wrapper',
            'cart/cart_item_list': '._cart_item_list',
            'cart/cart_total_cost': '._cart_total_cost'
        }
    });

**Comment by kharanenka** [comment]
You need to debug findPosition method, when you remove offer. 
Your problem is that at the time of removing of cart position, findPosition method can`t find position in database.
