### ISSUE TITLE
Adding Shipping and Billing Addresses to Orders

### ISSUE THREAD

**Issue by Cambrai1** [oc-shopaholic/oc-shopaholic-plugin#207]
Hello,

I've been looking through the documentation and I cannot work out how to attach shipping or billing data to the orders when using MakeOrder component. any help would be greatly appreciated.

**Comment by kharanenka** [comment]
Hi!

You can send address fields in **"shipping_address"/"billing_address"** objects. In this case, a new shipping/billing address will be created. You can send address ID in  **"shipping_address"/"billing_address"** objects. In this case, shipping/billing address will be filled from existing address.

https://github.com/oc-shopaholic/oc-shopaholic-plugin/wiki/MakeOrder

```javascript
var data = {
    'order': {
        'payment_method_id': 1,
        'shipping_type_id': 2,
        'shipping_price': 10.5,
        'property': {
            'address': '...',
            'city': 'Minsk'
        }
    },
    'user': {
        'email': 'test@test.com',
        'name': 'Andrey'
    },
    'shipping_address': {
        'id': 10  //Address data of user with ID == 10 will be save in order
    },
    'billing_address': {
        //New billing address will be created for user.
        'country': 'Belarus',
        'address1': 'test 1',
        'address2': 'test 2'
    }
};

$.request('MakeOrder::onCreate', {
    'data': data
});
```
