### ISSUE TITLE
How to send price type to  cartPositionItem?

### ISSUE THREAD

**Issue by Borowing** [oc-shopaholic/oc-shopaholic-plugin#208]
Hi,
How i can to send price type or my custom price to cartPositionItem?

**Comment by kharanenka** [comment]
Hi! You can switch active price type with using `PriceTypeHelper::instance()->switchActive('b2b');` method.
You can call method in onInit() unction in layout/page section. It is allow you to display catalog in different price types.

**Comment by kharanenka** [comment]
For example:

```php
function onInit()
{
    PriceTypeHelper::instance()->switchActive('b2b');
}
```
