### ISSUE TITLE
Cart::onAdd not create sequence position cart

### ISSUE THREAD

**Issue by phivh** [oc-shopaholic/oc-shopaholic-plugin#210]
Hello, 
I was follow guide (https://github.com/oc-shopaholic/oc-shopaholic-plugin/wiki/Cart) but when I sent an Ajax to create multi cart position it's seem not working. What i'm doing wrong.
```
var data = { 'cart' : [{offer_id: 1, quantity: 2}, {offer_id: 2, quantity: 1}] };
$.request('Cart::onAdd', {
                'data': data
});
```
After ajax sent then only one cart position with offer_id = 2 is created which not my expected must be create 2 position.

**Comment by kharanenka** [comment]
Hi! It is bug. We will fix it in next update.

**Comment by kharanenka** [comment]
Bug is fixed, changes will be added in next update.
