### ISSUE TITLE
[Question] [Properties Plugin] Adding custom field types

### ISSUE THREAD

**Issue by mrelevance** [oc-shopaholic/oc-shopaholic-plugin#211]
Hi, I am looking at using this plugin for a project of mine and I had a question about the properties plugin before I decide to buy it.

Is it possible to be able to add custom property types other than the built-in types? I would like to be able to add a custom select type where the options are folder names on the filesystem for functionality specific to my project.

Thanks

**Comment by kharanenka** [comment]
Hi! 
To solve your issue, you can create property with "select" type. For available property values, you can fill pairs: folder path -> folder name for backend. 

As result, you get "nice folder name" in backend and folder path in frontend.
