### ISSUE TITLE
Can't create category when VK good plugin is enabled

### ISSUE THREAD

**Issue by ghost** [oc-shopaholic/oc-shopaholic-plugin#213]
Hello,

I'm testing the shopaholic ecosystem for a future project and encountered bug on your demo shop.

When I try to create a category, I get an error : 

 > "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'category_vk_id' at row 1 (SQL: insert into `lovata_shopaholic_categories` (`active`, `name`, `slug`, `code`, `external_id`, `preview_text`, `description`, `category_vk_id`, `search_synonym`, `nest_left`, `nest_right`, `updated_at`, `created_at`) values (1, Test, test, , , , , , , 17, 18, 2019-08-21 10:12:55, 2019-08-21 10:12:55))" on line 664 of /var/www/demo.shopaholic.one/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php

It seems related to VK Goods plugin

I also attach a GIF

https://gyazo.com/8d7972be00ca07965d89e48f09ce2f1c

Best regards,

Alex

**Comment by kharanenka** [comment]
Fixed in version 1.0.2
