### ISSUE TITLE
Unable to add products to order through backend

### ISSUE THREAD

**Issue by igor-tv** [oc-shopaholic/oc-shopaholic-plugin#214]
When I create an order manually through the backend, I have a problem. I create a position, categories in place, but products do not appear in the drop-down list. After changing the category, products are loaded, but offers are not loaded. The number of trading offers for all products is greater than zero.

The settings "When you receive a list of active products, check for active offers" and "Check the available quantity of the product when creating an order" I tried to turn on and off - the result does not change. Trading offers are not loading.

System build: 458
Shopaholic 1.22.5
Google Chrome 76.0.3809.132 on MacOS

**Comment by lautsevich** [comment]
Thx for the report. We'll check your question soon.

**Comment by kharanenka** [comment]
Bug is fixed, changes will be added in next update.
