### ISSUE TITLE
Search for Shopaholic plugin can't search offers content?

### ISSUE THREAD

**Issue by buzmate** [oc-shopaholic/oc-shopaholic-plugin#215]
Hello I have an e-shop using Shopaholic and bought Search plugin. One of my requirements was to be able to search the products using the Vendor code which was fine but only for the main product. The plugin seems that doesn't do any search in the offer items within each product. Is there an option to enable this?

Thank you,
Marios

**Comment by lautsevich** [comment]
Hi @buzmate, It seems we don't have search functionality for the offers. We'll discuss it next week and give you the answer.

**Comment by buzmate** [comment]
OK lautsevich thank you for considering this as an enhancement. That is very important for the implementation as all products have at list one offer to have the price tag so that forces us to add the identifiers, such as vendor code/barcode on the offer instead of the product.

**Comment by kharanenka** [comment]
Hi @buzmate! 
You can try to fill in **'search_synonym'** field manually or fill in **'search_content'** field automatically.

**Comment by buzmate** [comment]
Can you explain what do you mean by feel the search_content field automatically?

**Comment by kharanenka** [comment]
You can collect barcodes/codes from offers in one string (for example: "10045745 10045776 10045779" )

**Comment by buzmate** [comment]
Yes I understand this but can this be done automatically? How can I set the search_content field to be always the collection of offer's barcodes while updating, the list of offers per product?

**Comment by kharanenka** [comment]
You can add event listeners for Offer model. For example: afterCreate, afterSave, afterDelete. See more in [OctoberCMS dosc](https://octobercms.com/docs/database/model#events).

**Comment by kharanenka** [comment]
for example: 
```php
Offer::extend(function($obOffer) {
    $obOffer->bindEvent('model.afterSave', function() use ($obOffer) {
        if ($obOffer->code != $obOffer->getOriginal('code')) {
                //  get product object and save search_content
        }
    });
});

```

**Comment by buzmate** [comment]
OK thank you. Kharanenka, got it. I might do it over product model on "afterFetch" event and fetch all offers to build the search_content string as the catalog now has almost 1000 offers so I need away to populate all previous entries.

**Comment by kharanenka** [comment]
You can create [seeder](https://octobercms.com/docs/database/structure#seeder-structure)

**Comment by buzmate** [comment]
Oh yes this looks more appropriate. Thanks.
