### ISSUE TITLE
Discount by user group.

### ISSUE THREAD

**Issue by buzmate** [oc-shopaholic/oc-shopaholic-plugin#216]
Hello. Is there a way to apply discount only to a specific group of users? Let's say I need to separate my clients to retail and wholesale.

**Comment by kharanenka** [comment]
Hi @buzmate!
Now there is no such possibility. We have plans to develop a plugin for user loyalty system.

Do you need to show different prices for different user groups in the catalog or in the cart/checkout?

**Comment by buzmate** [comment]
Both. Basically I I want my retail clients to see the retail prices and my wholesale clients to see the discounted prices the get that will then resale the items. So in the check out each group will also have different final prices.

**Comment by kharanenka** [comment]
Now I can advise you to create one type of price. Add custom logic that will check user group and activate discounted price type.
For example:
```php

use Lovata\Buddies\Facades\AuthHelper;
use Lovata\Shopaholic\Classes\Helper\PriceTypeHelper;

$obUser = AuthHelper::getUser();
if (empty($obUser) || /** check user group **/) {
    return;
}

$obActivePriceType = PriceTypeHelper::instance()->findByCode('discount');
if (!empty($obActivePriceType)) {
    PriceTypeHelper::instance()->switchActive($obActivePriceType->code);
}

```

**Comment by buzmate** [comment]
OK thank you kharanenka. I will check out the pricetypehelper and probably this will solve my problem as you suggested.
