### ISSUE TITLE
[Orders for Shopaholic v1.22.1] Unable to get shipping fee information from Cart component

### ISSUE THREAD

**Issue by pikanji** [oc-shopaholic/oc-shopaholic-plugin#218]
I'm trying get price information including shipping fee with cart component in Twig.
However, there seems no way to get this information via Twig.
I have 2 questions regarding this.

### 1. Should Cart::onGetData not include shipping fee?
I'm expecting to get price information including shipping fee, when the cart data in DB has shipping_type_id set.
For example, the data returned by these methods below do not include the shipping fee.

\Lovata\OrdersShopaholic\Components\Cart::onGetData
\Lovata\OrdersShopaholic\Components\Cart::getTotalPrice

Is this an expected behavior?
If not, I'm willing to contribute for the fixation.

### 2. Is `Cart::onGetData` an Ajax handler method?
It seems it is, but the form of the response is different from other Ajax handlers.
Using `Result` class to make the response like other handlers sounds more reasonable to me.
If my guess is correct, then I won't be able to use this method from Twig.
In that case, I like to have similar method available in Twig code, or method to get shipping fee.
This one also, I'm willing to contribute.

Thanks.

**Comment by kharanenka** [comment]
Hi!
I merged your PR, Thanks for your contributions and ideas. I am very pleased to receive ideas and improvements from you.

**Comment by pikanji** [comment]
Thanks so much! I'm very glad that I could contribute also!
