### ISSUE TITLE
Call to a member function getIDList() on null

### ISSUE THREAD

**Issue by Exodon** [oc-shopaholic/oc-shopaholic-plugin#221]
I'm using the theme : **Sneakers E-Commerce Theme** and when trying to reach this url : 
http://localhost/shoe/man

 I get this error : 
EXCEPTION
Cms\Classes\CmsException
"Call to a member function getIDList() on null"
C:\laragon\www\shoe/themes/lovata-shopaholic-sneakers/pages/catalog.htm line 95

```
//Get product list with filter by category
    $obCategoryProductList = $this->ProductList->make()->active()->sort($sActiveSorting)->category($obCategory->id);
  
    //Get property list for filter panel
    $obProductPropertyList = $obCategory->product_filter_property;
    $obOfferPropertyList = $obCategory->offer_filter_property;
  
    foreach($obProductPropertyList->getIDList() as $iPropertyID) {
        $arFilterValueTemp = $arFilterValue;
        if (isset($arFilterValueTemp[$iPropertyID])) {
            unset($arFilterValueTemp[$iPropertyID]);
        }
```

![2019-09-25 12_56_45-Exception](https://user-images.githubusercontent.com/3321409/65594928-f67bb600-df93-11e9-869b-c49f1819987a.png)

This happend on the product level as well : 

![2019-09-25 13_08_14-Exception](https://user-images.githubusercontent.com/3321409/65595680-90902e00-df95-11e9-999f-5f2d86d4a539.png)

C:\laragon\www\shoe/themes/lovata-shopaholic-sneakers/pages/product.htm line 62

**Comment by kharanenka** [comment]
Hi! What plugins did you install?

**Comment by Exodon** [comment]
Hi...I have this ones : 
![image](https://user-images.githubusercontent.com/3321409/67084363-1c643700-f19d-11e9-9cf1-2a868e7e5de9.png)

**Comment by kharanenka** [comment]
Please, install [Properties for Shopaholic](https://octobercms.com/plugin/lovata-propertiesshopaholic) plugin.
