### ISSUE TITLE
mighty seo custom model integration

### ISSUE THREAD

**Issue by ed-garas** [oc-shopaholic/oc-shopaholic-plugin#227]
I'm struggling to make my custom model work with plugin, I'm trying to do everything by docs, add 

`{% placeholder seo_tags default %}
  {% component 'SeoToolbox' %}
{% endplaceholder %}`

in placeholder and then I need to add 

`{% set obProduct = ProductPage.get() %}
{% set arSEOParams = {'product': obProduct} %}
{% put seo_tags %}
  {% component 'SeoToolbox' model=obProduct params=arSEOParams %}
{% endput %}`

in my template...so if I do that (in my case):
`{% set obBusiness = business.get() %}
{% set arSEOParams = {'business': obBusiness} %}
{% put seo_tags %}
{% component 'SeoToolbox' model=obBusiness params=arSEOParams %}
{% endput %}`

i'm getting error like this:
An exception has been thrown during the rendering of a template ("Property [seo_param] does not exist on this collection instance.").

Model is add to 'seo_models' array in app.php

**Comment by lautsevich** [comment]
Hi @ed-garas, which version of Mighty SEO do you use?

**Comment by ed-garas** [comment]
> Hi @ed-garas, which version of Mighty SEO do you use?

https://octobercms.com/plugin/lovata-mightyseo
version: 1.1.2

**Comment by lautsevich** [comment]
Thx, for your report! We'll check it.

**Comment by ed-garas** [comment]
> Thx, for your report! We'll check it.

i's probably not a bug, maybe just a documentation issue

**Comment by kharanenka** [comment]
Please update plugin to last version 1.1.4
If you will reproduce error after updating, then send your SEO template from backend

**Comment by ed-garas** [comment]
> Please update plugin to last version 1.1.4
> If you will reproduce error after updating, then send your SEO template from backend

Thank you! it's seems that everything is working now.

**Comment by kharanenka** [comment]
Please, close issue if everything is working correctly
