### ISSUE TITLE
[Properties for shopaholic] add setting to hide import from csv button

### ISSUE THREAD

**Issue by mjauvin** [oc-shopaholic/oc-shopaholic-plugin#228]
Add a setting under the `Import` tab for Properties for shopahilic:

- Hide "import from CSV" button for properties

**Comment by mjauvin** [comment]
Any progress on this?

**Comment by kharanenka** [comment]
Do you mean this settings? http://joxi.ru/BA089jOTPqe9VA

**Comment by mjauvin** [comment]
yes

--
Marc

**Comment by kharanenka** [comment]
Can I close this issue?

**Comment by mjauvin** [comment]
yes.
