### ISSUE TITLE
Save ProductList sorting in Session

### ISSUE THREAD

**Issue by kordima** [oc-shopaholic/oc-shopaholic-plugin#229]
I want to save sorting in Session. 
I load sorting in method onInit page:
```
function onInit()
{
    $sorting = Session::get("product.list.sorting");
    if ($sorting) {
        $this->ProductList->setProperty('sorting', $sorting);
        $this->ProductList->setActiveSorting(); // this protected method
    }
}
```
However, the setActiveSorting method is protected.
How do I set the SortingElementList >$sSorting property ?
Can make setActiveSorting method public ?

**Comment by lautsevich** [comment]
Thx! Fixed.

**Comment by kharanenka** [comment]
You need to transfer alue from session to sort() method in ProductCollection class.
For example:
```
function onInit()
{
    $sorting = Session::get("product.list.sorting");
    $this['my_sorting'] = $sorting;
}
==
{% set obProductList  = ProductList.make().sort(my_sorting) %}

```

**Comment by kordima** [comment]
Yes, I can make my variable, however I wanted to use the SortingElementList-> getSorting () method. Saving sorting is necessary and the SortingElementList class is no longer needed.
Let's add the ability to set SortingElementList->sSorting.

**Comment by kordima** [comment]
My solution through a variable:
```
function onInit()
{
    // Init sorting
    $curSorting = Session::get('product.list.sorting', $this->ProductList->property('sorting'));
    $newSorting = Input::get('sort');
    if (!empty($newSorting) && ($newSorting != $curSorting)) {
        Session::put('product.list.sorting', $newSorting);
        $curSorting = $newSorting;
    }
    $this['sSorting'] = $curSorting;
}

```
If the authors adds setter, then you can write
`
$this->ProductList->setSorting($curSorting) 
`
and then ProductList->getSorting() will work also.

Андрей, just do it )))

**Comment by kharanenka** [comment]
Hi! I think this is bad decision, because your example is perfect for solving your problem. If I add setSorting() method to component class, then we may get problems with fact that during template rendering several component objects will be created and the sort value will be in one of them. Making storage in a static variable would also be a bad decision.

**Comment by kordima** [comment]
ok
