### ISSUE TITLE
[Filters] How to filter by property without displaying in filter panel

### ISSUE THREAD

**Issue by mrelevance** [oc-shopaholic/oc-shopaholic-plugin#232]
So, I am trying to create a featured products slider on a homepage of a website. I am trying to use the properties & filters plugin to accomplish this by adding a switch property called featured and creating a separate property group specifically for this property in hopes to hide it from the filter panel.

However, it is displaying even though I only am trying to use the main property group.
See code below:
```twig
{% set obPropertyList = FilterPanel.getProductPropertyList(['main'], obProductList) %}

        {% for obProperty in obPropertyList if obProperty.hasValue() %}
            <li class="filter-list__item filter-list-item">
                {# Render filter name #}
                <strong class="filter-list-item__header">{{ obProperty.filter_name }}</strong>

                <div class="grid-x grid-margin-x grid-margin-y large-up-2">
                    {# Get Filter type#}
                    {% set sFilterType = obProperty.filter_type %}

                    {# Get property value list #}
                    {% set obPropertyValueList = obProperty.property_value.sort() %}

                    {% set filter_input_values = input('product['~obProperty.id~']') %}

                    {# Render filter with type == checkbox #}
                    {% if sFilterType == 'checkbox' %}
                        {% for obValue in obPropertyValueList %}
                            <div class="cell">
                                <label>
                                    <input type="checkbox" name="product[{{ obProperty.id }}][]"
                                           value="{{ obValue.slug }}"
                                           {% if obValue.slug in filter_input_values %}checked{% endif %}/>
                                    {{ obValue.value }}
                                </label>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </li>
        {% endfor %}
```
But when I go to the front-end, I can see it trying to display that filter
![Screenshot from 2019-12-11 10-00-54](https://user-images.githubusercontent.com/5429872/70637631-28003700-1bfd-11ea-8417-c5c6aa5377ca.png)

Here is a screenshot of my "main" property set
![Screenshot from 2019-12-11 10-02-34](https://user-images.githubusercontent.com/5429872/70637781-6a297880-1bfd-11ea-98b3-4a71829e1d07.png)

So, I guess is there a way I can filter by a property without making them show up in the filter panel. Or is there a better way of accomplishing something like this?

Thanks

**Comment by mrelevance** [comment]
Seems like promo blocks will work after looking at it a bit more.

**Comment by kharanenka** [comment]
You are right, promo blocks solve such problems as special lists of products. For example, popular products on index page
