### ISSUE TITLE
Question: why onAjaxRequest method deprecated?

### ISSUE THREAD

**Issue by kordima** [oc-shopaholic/oc-shopaholic-plugin#234]
In Shopaholic update 1.26 method onAjaxRequest was marked @deprecated.
How to do ajax requests right now?

**Comment by kharanenka** [comment]
Hi! onAjaxRequest method is not needed because onAjax is a standard method in OcotberCMS.
See more information [here](https://octobercms.com/docs/ajax/handlers#calling-handlers)
http://joxi.ru/J2bk6bytGMQewA
