### ISSUE TITLE
CSV Import Error - Slug Already Taken

### ISSUE THREAD

**Issue by MatVR** [oc-shopaholic/oc-shopaholic-plugin#239]
There are two field types that cause an error with CSV Imports - the **text field (number)** and **text field (wysiwyg)** fields. When using either of these field types in a 'property set' they cause the CSV import to fail for that particular field and will deliver a _'slug already taken'_ error message. Changing these to a different type of text field removes the error and then the import works correctly.

This error can be replicated consistently when importing. The same bug has been observed at times when saving individual records, but the behaviour is, unfortunately, not consistent in the same way as it is with importing.

**Comment by kharanenka** [comment]
I could not reproduce your bug. It is not related with type of field. There is no logic in code to save the property value and field type. I will add a small fix in properties plugin, that import does not fail if an error occurs. If you have problems, I will expect from you the results of getValueObject() method debug in file plugins/lovata/propertiesshopaholic/classes/helper/CommonPropertyHelper.php

**Comment by MatVR** [comment]
Hi Andrey,

Please see the following screen recording where we replicate this error;

<goog_1847420541>
https://workdrive.zohoexternal.com/external/19aFS0OJuKR-KrpNP

For the sake of simplicity, we have shown how to replicate this bug when
saving one simple record. If the 'Text-Number' field is used we receive the
error consistently, if we change the field to a regular 'Text only' field,
then the bug disappears.

*This exact same issue is replicable in the same way when importing*. If
'Text -Number' (or WYSIWYG Field) is used the Import will fail. If they are
removed, the import will run successfully.

Please let me know if you require an additional screen recording to show
the same bug when importing or whether this gives you enough to work with.

Cheers,
Mat

*—*

*Mat Lewis*
Co-Founder & CEO

Facebook <https://www.facebook.com/ViewRetreats/> | Instagram
<https://www.instagram.com/viewretreats/> | Pinterest
<https://au.pinterest.com/viewretreats/> | Twitter
<https://twitter.com/viewretreats> | Blog
<http://www.viewretreats.com/blog/>

View Retreats, Box 915, 585 Little Collins Street, Melbourne, VIC 3000,
Australia
Ph. 1300 368 337 | Int. +61 3 9013 4858 | www.viewretreats.com

For each new booking, we plant a native tree somewhere in Australia. Read
more <https://www.viewretreats.com/blog/make-a-booking-plant-a-tree/>.

<http://goog_923369052>
<https://www.viewretreats.com/blog/top-50-romantic-getaways-in-australia/>

*PLEASE NOTE:* Rate & availability information is correct at the time of
sending but is subject to change at any time without notice. Unless clearly
specified otherwise, we are not holding any rooms for your enquiry. For
more information view our terms of service
<https://www.viewretreats.com/terms-condition>. We acknowledge the
Indigenous people of Australia as the Traditional Custodians of the lands
where we live, learn and work. We pay our respect to them and their
cultures, and to elders both past and present.

**Comment by kharanenka** [comment]
Please, check if bug is reproducing in 1.10.0 "Properties" plugin version.

**Comment by MatVR** [comment]
Hey Andrey,

Good news, we can no longer replicate this bug. Thanks for your assistance.

Cheers,
Mat

*—*

*Mat Lewis*
Co-Founder & CEO

Facebook <https://www.facebook.com/ViewRetreats/> | Instagram
<https://www.instagram.com/viewretreats/> | Pinterest
<https://au.pinterest.com/viewretreats/> | Twitter
<https://twitter.com/viewretreats> | Blog
<http://www.viewretreats.com/blog/>

View Retreats, Box 915, 585 Little Collins Street, Melbourne, VIC 3000,
Australia
Ph. 1300 368 337 | Int. +61 3 9013 4858 | www.viewretreats.com

For each new booking, we plant a native tree somewhere in Australia. Read
more <https://www.viewretreats.com/blog/make-a-booking-plant-a-tree/>.

<http://goog_923369052>
<https://www.viewretreats.com/blog/top-50-romantic-getaways-in-australia/>

*PLEASE NOTE:* Rate & availability information is correct at the time of
sending but is subject to change at any time without notice. Unless clearly
specified otherwise, we are not holding any rooms for your enquiry. For
more information view our terms of service
<https://www.viewretreats.com/terms-condition>. We acknowledge the
Indigenous people of Australia as the Traditional Custodians of the lands
where we live, learn and work. We pay our respect to them and their
cultures, and to elders both past and present.
