### ISSUE TITLE
CSV Import Error - 'Ignored' Columns Deleted

### ISSUE THREAD

**Issue by MatVR** [oc-shopaholic/oc-shopaholic-plugin#240]
When performing a CSV import, if columns are marked as **'ignore'**, these same columns are deleted during the import process rather than being ignored. This means that the import function currently only works to 'create' records rather than 'update' existing records.

**Comment by kharanenka** [comment]
Hi!


I tested the import. My test cases:
1. Uploaded CSV file with fields: external_id, name, code. Import completed successfully, new products were created.
2. Uploaded CSV file with changed field values: name, code. Import completed successfully, the values ​​of the product fields were updated.
3. Uploaded CSV file  with fields: external_id, name, code. "code" field not selected for import (http://joxi.ru/MAjg3QJUxYbE1r). Import completed successfully, the values ​​of the product fields were updated. "code" field has not changed.
4. Uploaded CSV file with fields: external_id, name, code. "code" field is marked as ignore fields for import. Import completed successfully, the values ​​of the product fields were updated. "code" field has not changed.

I can not reproduce your bug.

**Comment by lautsevich** [comment]
@MatVR, could you provide more details, please?

**Comment by MatVR** [comment]
Hi Andrey,

Thanks for your email.

This is the exact reason that I emailed Pavel about this feature in the
first place rather than raising a ticket. Maybe we're just misunderstanding
the feature entirely rather than experiencing a genuine bug.

Let's say we have an existing product with 20 fields, but we only want to
update 2 of these existing fields. We upload a spreadsheet with 20 fields,
but we ignore all except the *External ID, Name* + the two fields that
require updating. We mark all other 16 fields as 'Ignore'/

In this case... the 4 required fields are indeed updated correctly.
However, the 16 'ignored' fields are deleted rather than being 'ignored'.

Is this the way the system is designed to work? If not, can we send you a
screen-recording of how to replicate this issue?

Thanks,
Mat


*—*

*Mat Lewis*
Co-Founder & CEO

Facebook <https://www.facebook.com/ViewRetreats/> | Instagram
<https://www.instagram.com/viewretreats/> | Pinterest
<https://au.pinterest.com/viewretreats/> | Twitter
<https://twitter.com/viewretreats> | Blog
<http://www.viewretreats.com/blog/>

View Retreats, Box 915, 585 Little Collins Street, Melbourne, VIC 3000,
Australia
Ph. 1300 368 337 | Int. +61 3 9013 4858 | www.viewretreats.com

For each new booking, we plant a native tree somewhere in Australia. Read
more <https://www.viewretreats.com/blog/make-a-booking-plant-a-tree/>.

<http://goog_923369052>
<https://www.viewretreats.com/blog/top-50-romantic-getaways-in-australia/>

*PLEASE NOTE:* Rate & availability information is correct at the time of
sending but is subject to change at any time without notice. Unless clearly
specified otherwise, we are not holding any rooms for your enquiry. For
more information view our terms of service
<https://www.viewretreats.com/terms-condition>. We acknowledge the
Indigenous people of Australia as the Traditional Custodians of the lands
where we live, learn and work. We pay our respect to them and their
cultures, and to elders both past and present.

**Comment by kharanenka** [comment]
Yes, please send screen-recording on a.khoronenko@lovata.com email

**Comment by kharanenka** [comment]
Fixed in version 1.10.0 of Properties for Shopaholic plugin

**Comment by MatVR** [comment]
We've tested and this is working perfectly now. Thanks for your help.
