### ISSUE TITLE
[Lovata.PropertiesShopaholic] Property of type Checkbox list loses translation for its options' values

### ISSUE THREAD

**Issue by mjauvin** [oc-shopaholic/oc-shopaholic-plugin#250]
I have a LIVE website using `Lovata.PropertiesShopaholic` plugin and all the properties of type Checkbox List exhibit the same behavior: when the checkbox options value are translated, the translation just vanish after a few hours.

I cannot provide a procedure to reproduce this yet, but this is causing major issues for the non-default locale versions of the website.

**Comment by mjauvin** [comment]
I was able to reproduce the problem, but my setup is heavily modified and I'd like to test this on your demo site.

Is there a way for you to add the Rainlab.Translate plugin to the demo site for me to test this and provide a procedure to reproduce the problem?

**Comment by kharanenka** [comment]
Plugin Rainlab.Translate enabled  https://demo.shopaholic.dev/

**Comment by mjauvin** [comment]
Ok, I was able to reproduce the problem on the demo site linked above. Here it is:

- Under the `Settings->Properties`, click on the "Material" property
- Under the property values, click on `Spandex`
- Add a Russian translation for this property value (whatever)
- Save property

Now, under the `Catalog->Products`, select a product that has `Spandex` has material selected (or select "spandex" as one of its materials) and SAVE the product (with or without modifications).

Go back to the `Settings->Properties` and re-open the same property (material) and you will find the russian translation for the "spandex" property value is gone.

**Comment by mjauvin** [comment]
Pointer: problem is definitely happening in `CommonPropertyHelper::getValueObject()`:
```
            if (!empty($sLangValue)) {
                $obPropertyValue->setAttributeTranslated('value', $sLangValue, $sLangCode);
            } else {
                DB::table('rainlab_translate_attributes')
                    ->where('locale', $sLangCode)
                    ->where('model_id', $obPropertyValue->id)
                    ->where('model_type', PropertyValue::class)
                    ->delete();
            }
```

This is what's causing the translation to be lost.

**Comment by kharanenka** [comment]
Hi! I found an error in this place of logic. I will fix it soon.Thank you for your analysis and description of the bug.

**Comment by kharanenka** [comment]
Bug fixed in Properties for Shopaholic plugin (version 2.0.1)
