### ISSUE TITLE
Edit payment data from order

### ISSUE THREAD

**Issue by yehudahkay** [oc-shopaholic/oc-shopaholic-plugin#260]
Hi,

How can I remove the credit card details from the payment data tab in the order. I don't want this data saved in my database. Thank you.

**Comment by kharanenka** [comment]
Hi!
What payment gateway are you using?

**Comment by yehudahkay** [comment]
I am using the stripe gateway with the omnipay plugin

**Comment by kharanenka** [comment]
Sorry. We are not developer of Stripe plugin with payment gateway integration.
I can recommend that you contact with developer of Stripe plugin.

I can recommend that you can add to Order model beforeSave() event to clearing values ​​of payment fields.

**Comment by yehudahkay** [comment]
I am talking about this plugin https://octobercms.com/plugin/lovata-omnipayshopaholic it says lovata is the developer and links to this repository

**Comment by kharanenka** [comment]
You can pass arrays with keys "payment_gateway_purchase_data" and "payment_gateway_card_data" in request.
The values ​​of these fields will be transferred to payment gateway without saving to database.

**Comment by yehudahkay** [comment]
Where would I pass that? Currently my object looks like this:

'payment_method_id' => 1,
            'property'          => [
                'number'      => $data['card_number'],
                'expiryMonth' => $data['expiry_month'],
                'expiryYear'  => $data['expiry_year'],
                'cvv'         => $data['cvv']
            ]

**Comment by kharanenka** [comment]
I guess it should be like that
'order' => [
            'payment_method_id' => 1
],
 'payment_gateway_card_data'          => [
                'number'      => $data['card_number'],
                'expiryMonth' => $data['expiry_month'],
                'expiryYear'  => $data['expiry_year'],
                'cvv'         => $data['cvv']
            ]

**Comment by yehudahkay** [comment]
I had tried that but I got an error 'The number parameter is required'

**Comment by kharanenka** [comment]
Do you have last version of Omnipay plugin?

**Comment by yehudahkay** [comment]
I have the latest version of all the shopaholic plugins

**Comment by kharanenka** [comment]
Please, debug plugins/lovata/omnipayshopaholic/classes/helper/PaymentGateway.php class, extendCardData() method.

**Comment by yehudahkay** [comment]
I didn't see anyway there to do what you were saying. Trying this:

``
Order::saving(function($order){
            unset($order->payment_data->card);
            return $order;
        });
``
or this
``
Order::saving(function($order){
            unset($order->payment_data);
            return $order;
        });
`` 
both had issues.
I found I could change the lovato omnipay plugin as follows however I wish I could find a better way.
``
protected function sendPurchaseData()
    {
        $arPaymentData = (array) $this->obOrder->payment_data;
        $arPaymentData['request'] = $this->arPurchaseData;
        $this->obOrder->save();
        $arPaymentData['request']['card'] = $this->arCardData;

        $this->obOrder->payment_data = $arPaymentData;

        try {
            $this->obResponse = $this->obGateway->purchase($this->arPurchaseData)->send();
            unset($this->obOrder->payment_data);
        } catch (\Exception $obException) {
            $this->sResponseMessage = $obException->getMessage();
            unset($this->obOrder->payment_data);
            return;
        }
    }
``

**Comment by yehudahkay** [comment]
Trying this:

```
Order::saving(function ($order) {
            if (!empty($order->payment_data['request']['card'])) {
                unset($order->payment_data['request']['card']);
            }
            return $order;
        });
```
gives me an error - Indirect modification of overloaded property Lovata\OrdersShopaholic\Models\Order::$payment_data has no effect

The only way I've found to do it so far is to modify the lovata omnipay plugin:
```
protected function sendPurchaseData()
    {
        $arPaymentData = (array) $this->obOrder->payment_data;
        $this->obOrder->save();
        $arPaymentData['request'] = $this->arPurchaseData;
        $arPaymentData['request']['card'] = $this->arCardData;

        $this->obOrder->payment_data = $arPaymentData;

        try {
            $this->obResponse = $this->obGateway->purchase($this->arPurchaseData)->send();
            unset($arPaymentData['request']['card']);
        } catch (\Exception $obException) {
            $this->sResponseMessage = $obException->getMessage();
            unset($arPaymentData['request']['card']);
            return;
        }
    }
```

**Comment by yehudahkay** [comment]
Can't see anyway for that to work.

Also this:
```
Order::saving(function ($order) {
            unset($order->payment_data);
            unset($order->property['number']);
            unset($order->property['expiryMonth']);
            unset($order->property['expiryYear']);
            unset($order->property['cvv']);
        });
    }
```
Gives me error Indirect modification of overloaded property Lovata\OrdersShopaholic\Models\Order::$property has no effect

**Comment by kharanenka** [comment]
Do you have this line?
https://github.com/oc-shopaholic/oc-omnipay-shopaholic-plugin/blob/master/classes/helper/PaymentGateway.php#L407

**Comment by yehudahkay** [comment]
Ah you are correct I didn't have the latest version of the code
