### ISSUE TITLE
Coupon applied only for selected offers

### ISSUE THREAD

**Issue by alvaro-canepa** [oc-shopaholic/oc-shopaholic-plugin#261]
Now coupon was applied to any product/offer, just entering the coupon code, apply the discount to the order. It would be great if there was an option to apply coupon only for added products/offers on current coupon group. And, of course, apply the discount to the selected offers only, instead of the total order.

**Comment by kharanenka** [comment]
Hi! 
1. You must create coupon group.
2. You must link products/offers to the coupon group. ([http://joxi.ru/vAWdXbMtqG7zar](http://joxi.ru/vAWdXbMtqG7zar))
3. You must create a promo mechanism (1, 8, 13, 18)
4. You must link the promo mechanism with coupon group.

After applying the coupon, the promo mechanism will be applied only to those positions that are linked with coupon group.

**Comment by alvaro-canepa** [comment]
I follow this steps, but the coupon isn't applied only in the linked offer.

**I have this setting in Promo Mechanism.**
![image](https://user-images.githubusercontent.com/5142298/76857756-dc30df80-6834-11ea-8626-0fc68d0cea35.png)

I only have the offer **Modalidade 21KM - Lote promocional** linked to coupon group. But, when I add more offers (same product) to the cart, and apply the coupon code, the discount was applied to the total of the order, instead of the offer linked.
![image](https://user-images.githubusercontent.com/5142298/76858001-51041980-6835-11ea-9496-6f85b20bb09d.png)

The discount must be $20.00 instead of $34.00

**Comment by kharanenka** [comment]
Hi! Bug fixed in Coupons plugin, version 1.1.4
