### ISSUE TITLE
How to show product offers on front-end?

### ISSUE THREAD

**Issue by maartenmachiels** [oc-shopaholic/oc-shopaholic-plugin#262]
Hi, question, I'm testing out Shopaholic and it looks good! I'm trying out the offers inside products now, where you can have multiple prices for different colors or types of products. However, I don't see them appearing on the product detail page. Only the highest price applies and the information of product offers does not show. So my question is, is there any other plugin mandatory in order to get the option to select product offers?

**Comment by kharanenka** [comment]
Hi! Main shopaholic plugin supports displaying a list of offers and their prices out of the box. You can create a product and several offers. You can specify different prices for offers. You can render the list of offers on the product page. Switching the offer on the product page can change the block with the price. You can add this logic to your templates.

**Comment by maartenmachiels** [comment]
Hi, strange... I cannot get it to work in the default bootstrap theme... It doesn't show up. Am I missing a setting?

**Comment by kharanenka** [comment]
Bootstrap theme does not support choice of offer on product page from the box. We plan to add this feature to the bootstrap theme soon.

**Comment by snipiba** [comment]
> Bootstrap theme does not support choice of offer on product page from the box. We plan to add this feature to the bootstrap theme soon.
> 
> You can change template code yourself by adding an offer selection and a price changing.

some specific demo of workaround before it will be implemented to default bootstrap theme?

**Comment by lautsevich** [comment]
> some specific demo of workaround before it will be implemented to default bootstrap theme?

@snipiba, the Bootstrap theme is in maintenance mode as of today. We focus on the new [Tailwind theme](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme).
