### ISSUE TITLE
Displaying Price via ProductList

### ISSUE THREAD

**Issue by mwahlmueller** [oc-shopaholic/oc-shopaholic-plugin#266]
I've already read the documentation and found out that the price of a product can be found in the offers model. The problem is that i dont' know how to display the price correctly.
ProductList->Product->Offer->Price
Due offer is also a one to many realation, do i need a for loop once again like in the ProductList to access the Product?
This is what I've already tried:
  ` {% for obOffer in obProduct %}
    	{{ obProduct.offer.price }}
	{% endfor %}
`
and
  ` {% for obOffer in obProduct %}
    	{{ obOffer.price }}
	{% endfor %}
`

Thank you for this Plugin and for your help!

**Comment by kharanenka** [comment]
Hi!
Example 1:
```
{% set obOffer = obProduct.offer.first() %}
{{ obOffer.price }}
```

Example 2: 
```
{% for obOffer in obProduct %} {{ obOffer.price }} {% endfor %}
```

**Comment by mwahlmueller** [comment]
Thank you for your quick answer. It makes completely sense to write the code as you have showed me. For me it still does not work and I cant figure out why.

1. I created a Product in my Catalog and an offer for it. Product and offer are set to active.
<img width="808" alt="Bildschirmfoto 2020-03-27 um 12 27 43" src="https://user-images.githubusercontent.com/36930997/77751842-b40c6200-7026-11ea-8029-326c0583935a.png">
2. The "for-Loop" for my obProduct in my obProductList works fine and all the Products are getting displayed as you see [here](www.mawahl.com/shop).

To shorten my code this is what i wrote:
`{% set obProductList = ProductList.make().sort(ProductList.getSorting()).active() %}
{% if obProductList.isNotEmpty() %}
     {% for obProduct in obProductList %}
{% for obOffer in obProduct %} {{ obOffer.price }} {% endfor %}
{% endfor %}
{%endif%}
`

I also tried exactly this shortened code but it did not work tho display any offer information.
<img width="472" alt="Bildschirmfoto 2020-03-27 um 12 44 01" src="https://user-images.githubusercontent.com/36930997/77752870-ac4dbd00-7028-11ea-8190-9eb6f59c2263.png">

<img width="1045" alt="Bildschirmfoto 2020-03-27 um 12 44 53" src="https://user-images.githubusercontent.com/36930997/77753010-f636a300-7028-11ea-8127-5a1901fccad5.png">

**Comment by kharanenka** [comment]
I found mistake
Your code
```
{% for obOffer in obProduct %} 
```
Change to:
```
{% for obOffer in obProduct.offer %} 
```

**Comment by mwahlmueller** [comment]
Thank you so much!!
It worked :)
