### ISSUE TITLE
I get an error creating or editing a Product

### ISSUE THREAD

**Issue by antischoki** [oc-shopaholic/oc-shopaholic-plugin#270]
Shopaholic version 1.27.0

<img width="496" alt="Bildschirmfoto 2020-04-05 um 11 59 46" src="https://user-images.githubusercontent.com/63188067/78471914-16efae80-7735-11ea-9ca2-0e4271669055.png">

I recently updated from another version and this error occurs :(

**Comment by kharanenka** [comment]
Hi! You should reinstall Search for Shopaholic plugin with using command:
```
php artisan plugin:refresh Lovata.SearchShopaholic
```
