### ISSUE TITLE
Adding and Removing an Item from Catalog

### ISSUE THREAD

**Issue by aarjona1991** [oc-shopaholic/oc-shopaholic-plugin#273]
@kharanenka  Hi, i want to modify the "add-to-cart-button" partial to give the possibility to add & remove de item from the cart. How can i do that?? Thanks in advance!!!

**Comment by kharanenka** [comment]
Hi! Our components do not contain templates, so you can easily change the logic in the theme templates.
To add products to the cart, you must use [Cart::onAdd](https://shopaholic.one/docs#/modules/cart/component/component?id=onadd) method in your ajax requests.
To remove products from the cart, you must use the [Cart::onRemove](https://shopaholic.one/docs#/modules/cart/component/component?id=onremove) method in your ajax request.
You can restore cart positions with using [Cart::onRestore](https://shopaholic.one/docs#/modules/cart/component/component?id=onrestore) method in your ajax requests.
