### ISSUE TITLE
Change Price on Products according the currency selected

### ISSUE THREAD

**Issue by jpenaroche** [oc-shopaholic/oc-shopaholic-plugin#274]
Hello, I want to change the prices of my offers according with the selected currency. For example, if I have an offer with price of 20 and I select USD with a rate of 1, then the correct price will be (20 * 1) 'cause the rate that i selected for USD is one, but if i choose EUR with a rate of 1.2 the price then will be 20 * 1.2 . Then, when I choose my currency (USD or EUR) all prices should be updated in my page according with my configuration but it doesn't change! Is there a way to do it with the actual configuration...?, or there is another step that i have not seen it?.

**Comment by kharanenka** [comment]
Hi! Do you mean product or catalog page? Do you use [CurrencyList](https://shopaholic.one/docs#/modules/currency/component/component?id=currencylist) for switching active currencies?
