### ISSUE TITLE
Sneakers theme no partials available in backend

### ISSUE THREAD

**Issue by gurpritsingh** [oc-shopaholic/oc-shopaholic-plugin#276]
HI, I have installed sneakers theme version 1.1.7 on a fresh installation of october with all the plugins mentioned in the documentation.

The issue is that there are 2 partials (header.htm and footer.htm) available in the partials section but when I checked the theme's code it has many partials.
I am new to october so might have some knowledge gaps but october documentation  says that they don't support nested partials. 
Please help me fixing the issue , I tried going through documentation and github issues but haven't found any fix yet. @kharanenka

**Comment by kharanenka** [comment]
Hi @gurpritsingh !
Editing code through the backend is only suitable for simple projects. Therefore, OctoberCMS only supports mapping partial to backend at the first level of folder nesting.
To develop a large themes, it is inconvenient to keep partials at the same level of nesting. It is more convenient to group them into folders. For example, all partials for products are in "product" folder.

I recommend that you use any code editor, for example PHPStorm.

**Comment by lautsevich** [comment]
Hi @gurpritsingh!

Thx for the purchase. The Sneakers theme includes nested three of the partials for better DX. We believe that the development process should be in your IDE instead of the backend area of the project.

As for missing partials, October itself doesn't show nested partials, unfortunately.

So this is not a mistake, this is a feature.

**Comment by gurpritsingh** [comment]
Hi,
Thanks for the quick reply.
I have one last question is there any documentation around this ? Like how
many partials / components are provided by the theme and how to use them ?

Thanks,
Gurprit.

**Comment by gurpritsingh** [comment]
One more issue is that when I add a product and visit the page I see that the theme tries to access webp image but I uploaded a jpg file. so it doesn't get any image and 404's. same happens with the slider. Does the theme automatically

**Comment by kharanenka** [comment]
The folder structure is created by the developers themselves. There are no rules or recommendations in OctoberCMS documentation.
