### ISSUE TITLE
Adding Fondy Payment Gateway to site

### ISSUE THREAD

**Issue by Emilianissimo** [oc-shopaholic/oc-shopaholic-plugin#277]
Hello, dear developers of Shopaholic plugin. I have a very huge problem. I really don't understand how to add custom gateway. I was added omnipay to my october cms, made new plugin, added fondy omnipay extension. In your docs I saw you wrote about adding custom gateway. I made new plugin with this code like in docs:
```php
<?php namespace Emilian\FondyPaymentGateway;

use System\Classes\PluginBase;
use Emilian\FondyPaymentGateway\Classes\Helpers\FondyPayment;
use Emilian\FondyPaymentGateway\models\FondyGateway;
use Omnipay\Omnipay;
use Event;
use \Lovata\OrdersShopaholic\Models\PaymentMethod;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        Omnipay::getFactory()->register('fondy');
        Event::listen(PaymentMethod::EVENT_GET_GATEWAY_LIST, function() {
            $arPaymentMethodList = [
                'fondy' => 'Fondy',
            ];
   
            return $arPaymentMethodList;
           });
           PaymentMethod::extend(function ($obElement) {
            /** @var PaymentMethod $obElement */
   
            $obElement->addGatewayClass('fondy', FondyGateway::class);
           });
    }
}

```
After there was an Interface examples, but I didn't get what I need to write there. 
Can I find anywhere examples of ready code? And how i need to collate it with front-end? I made payment-type un my admin panel, and it showing inside my checkout form, but where i need to put this code (from fondy docs)?
```php
$gateway = Omnipay::create('Fondy');
$gateway->setPaymentKey($paymentKey);
$gateway->setMerchantId($merchantId);

$request = $gateway->purchase([
    'transactionId' => 1234,
    'amount' => 1000,
    'currency' => 'EUR',
    'description' => 'Order description',
    'return_url' => 'http://www.example.com/order/complete',
]);

$response = $request->send();

if ($response->isRedirect()) {
    // $response->getRedirectUrl()
}
```
I understand there is a controller, which checking payment type, but where is it? And am I right in plugin creating? Help me, please.

With respect, Emilian,

**Comment by Emilianissimo** [comment]
> Hello, dear developers of Shopaholic plugin. I have a very huge problem. I really don't understand how to add custom gateway. I was added omnipay to my october cms, made new plugin, added fondy omnipay extension. In your docs I saw you wrote about adding custom gateway. I made new plugin with this code like in docs:
> 
> ```
> <?php namespace Emilian\FondyPaymentGateway;
> 
> use System\Classes\PluginBase;
> use Emilian\FondyPaymentGateway\Classes\Helpers\FondyPayment;
> use Emilian\FondyPaymentGateway\models\FondyGateway;
> use Omnipay\Omnipay;
> use Event;
> use \Lovata\OrdersShopaholic\Models\PaymentMethod;
> 
> class Plugin extends PluginBase
> {
>     public function registerComponents()
>     {
>     }
> 
>     public function registerSettings()
>     {
>     }
> 
>     public function boot()
>     {
>         Omnipay::getFactory()->register('fondy');
>         Event::listen(PaymentMethod::EVENT_GET_GATEWAY_LIST, function() {
>             $arPaymentMethodList = [
>                 'fondy' => 'Fondy',
>             ];
>    
>             return $arPaymentMethodList;
>            });
>            PaymentMethod::extend(function ($obElement) {
>             /** @var PaymentMethod $obElement */
>    
>             $obElement->addGatewayClass('fondy', FondyGateway::class);
>            });
>     }
> }
> ```
> 
> After there was an Interface examples, but I didn't get what I need to write there.
> Can I find anywhere examples of ready code? And how i need to collate it with front-end? I made payment-type un my admin panel, and it showing inside my checkout form, but where i need to put this code (from fondy docs)?
> 
> ```
> $gateway = Omnipay::create('Fondy');
> $gateway->setPaymentKey($paymentKey);
> $gateway->setMerchantId($merchantId);
> 
> $request = $gateway->purchase([
>     'transactionId' => 1234,
>     'amount' => 1000,
>     'currency' => 'EUR',
>     'description' => 'Order description',
>     'return_url' => 'http://www.example.com/order/complete',
> ]);
> 
> $response = $request->send();
> 
> if ($response->isRedirect()) {
>     // $response->getRedirectUrl()
> }
> ```
> 
> I understand there is a controller, which checking payment type, but where is it? And am I right in plugin creating? Help me, please.
> 
> With respect, Emilian,

**Comment by Emilianissimo** [comment]
After register my gateway into plugin i found in my PaymentType settings in backend panel button to attach payment gateway to my type and found fondy there. But after saveing i got an error:
```error
"Class '\Omnipay\fondy\Gateway' not found" on line 86 of E:\OSPanel\domains\toureastinfo\vendor\omnipay\common\src\Common\GatewayFactory.php
```

**Comment by Emilianissimo** [comment]
I made my plugin boot like that:
```php
 public function boot()
    {
        
        Event::listen(PaymentMethod::EVENT_GET_GATEWAY_LIST, function() {
            $arPaymentMethodList = [
                'fondy' => 'Fondy',
            ];
   
            return $arPaymentMethodList;
           });

         PaymentMethod::extend(function ($obElement) {
            /** @var PaymentMethod $obElement */
   
            $obElement->addGatewayClass('fondy', FondyGateway::class);
           });
           
           Omnipay::getFactory()->register(FondyGateway::class);
       
    }
```
Error diasbled, hope i made it right, but there is still a problem, where i gonna add my gateway redirect and sending data function?

**Comment by Emilianissimo** [comment]
I made it capitalize and it works
```php 
Omnipay::getFactory()->register('fondy');
to
Omnipay::getFactory()->register('Fondy');
```
Still have problem with sending data (understanding where and how)

**Comment by kharanenka** [comment]
Hi! 
You can find example of payment gateway in [PaymentGateway](https://github.com/oc-shopaholic/oc-omnipay-shopaholic-plugin/blob/master/classes/helper/PaymentGateway.php) class.

You can extend PaymentGateway class and will add your custom logic for your payment gateway

**Comment by Emilianissimo** [comment]
> Hi!
> You can find example of payment gateway in [PaymentGateway](https://github.com/oc-shopaholic/oc-omnipay-shopaholic-plugin/blob/master/classes/helper/PaymentGateway.php) class.
> 
> You can extend PaymentGateway class and will add your custom logic for your payment gateway .
> 
> P.S. For some omnipay payment gateways, this class works out of the box.

Thanks, will try, will write later about progress :). But laso there is a problem with extend method, it doesn't exits in 
```php
use \Lovata\OrdersShopaholic\Models\PaymentMethod;
```

**Comment by kharanenka** [comment]
i mean ```class MyClass extends PaymentMethod```

**Comment by Emilianissimo** [comment]
Sorry, again me. I made my plugin like:
```php
public function boot()
    {
        PaymentMethod::extend(function ($obElement) {
            /** @var PaymentMethod $obElement */
   
            $obElement->addGatewayClass('fondy', FondyGateway::class);
           });
           
        
        Event::listen(PaymentMethod::EVENT_GET_GATEWAY_LIST, function() {
            $arPaymentMethodList = [
                'fondy' => 'Fondy',
            ];
   
            return $arPaymentMethodList;
           });

        
        Omnipay::getFactory()->register('Fondy');
       
        
    }
```
After i could see a selection field into my payment type Fondy:
![image](https://user-images.githubusercontent.com/48443034/80821462-3376ed80-8bf2-11ea-9b3c-e34b2aa6f3a6.png)
![image](https://user-images.githubusercontent.com/48443034/80821467-396cce80-8bf2-11ea-9f54-bcd737fc3fd7.png)
But there are some unexpected field. Oky.
After I made FondyGateway class which extends AbstractPaymentGateway.
In function preparePurchaseDate, I was added transactionId (coz my checkout form gave me message about requiring it).
But there is a problem. I don't understand is it works, or not. Coz this sending me error:
```php
public function boot()
    {
        PaymentMethod:extend(function ($obElement) {
            /** @var PaymentMethod $obElement */
   
            $obElement->addGatewayClass('fondy', FondyGateway::class);
           });
//But if I making like this error passing and i dunno works it or not
public function boot()
    {
        PaymentMethod::extend(function ($obElement) {
            /** @var PaymentMethod $obElement */
   
            $obElement->addGatewayClass('fondy', FondyGateway::class);
           });
```
In your docs was written about PaymentMethod:extend with one ":", but it says there is no method like this, also inside PaymentMethod there wasn't a  method.

Also you said i need to extend payment method with my class, where i gonna add some logic. But where after i need to handle it? Like hook. I really like a blind kitten. Thank you

**Comment by kharanenka** [comment]
I fixed error in documentation.

How does your payment gateway work? 

Typically, a payment gateway works like this:
1. Sending data to payment gateway with using sendPurchaseData() method.
2. Receive data from payment gateway and process response.
3. If a redirect is needed, then the user is redirected to the payment page.
4. After payment you must process response from the payment gateway. For example: change order status,  save transaction data. You control this logic in PaymentGateway class yourself
