### ISSUE TITLE
Wiki pages are publicly editable

### ISSUE THREAD

**Issue by stom66** [oc-shopaholic/oc-shopaholic-plugin#278]
It appears your wiki pages are publicly editable, as I discovered when following the links from the "Documentation" section of your plugin listing on the October website.

https://octobercms.com/plugin/lovata-shopaholic

It would be appreciated if you could restore the getting started guide, thanks!

**Comment by kharanenka** [comment]
Hi! Our new documentation is available [here](https://shopaholic.one/docs#/). Thanks for turning our attention to the wiki.
