### ISSUE TITLE
Cache not cleared when creating new product

### ISSUE THREAD

**Issue by ericp-mrel** [oc-shopaholic/oc-shopaholic-plugin#280]
Plug-in Version: 1.27.0
Toolbox Version: 1.29.0

I seem to be having some issues with regards to how this plug-in handles caching.

Whenever I add a new product, and I reload the front-end of the website. The Product does not appear, no matter how many times I try changing active to inactive and back again.

It is only ever displayed on the website if I manually run `php artisan cache:clear`.
I am using redis as my caching driver.

Once I have fully cleared the entire cache, then making the product active/inactive is reflected properly after saving. It seems this is only an issue when first creating the product and editing it seems to have no effect. But seems to get fixed after clearing the entire cache.

Obviously this is a huge problem as I cannot reasonably be expect to clear the entire cache manually every time my client decides to add new products to their website just so it shows up.

Here is the code I am using for the landing page to display the products:
```twig
{% set obProductList =  ProductList.make().sort(ProductList.getSorting()).active().category(obParentCategory.id) %}
```

**Comment by ericp-mrel** [comment]
Looks like this was a result of me using a custom sort, and I didn't have any sort of cache clearing for the ProductListStore sorting method.

**Comment by kharanenka** [comment]
Yes, you are right. When you add a custom sorting, you must add a cache clear for this sorting.

**Comment by rebaz88** [comment]
I still have this issue. I tried it even with our sorting, it still does not show up in frontend, but when I clear the entire cache, it shows up
