### ISSUE TITLE
How to Display Additional categories in category page for filter purpose 

### ISSUE THREAD

**Issue by kgangadhar** [oc-shopaholic/oc-shopaholic-plugin#283]
Hi, 
i'm trying to display all categories in category page , each product have multiple categories 
i'm using categories as filter filters in the product listing page .. but unable to display the additional categories which are selected at backend.. only able to display the categories which are selected form drop .. checked categories ( additional categories ) are not visible ...

pls provide me solution for this 
check this url => https://www.nuttynomnom.com/all-products

**Comment by kharanenka** [comment]
Hi! Can you give a more detailed example?

**Comment by kgangadhar** [comment]
will give an example 

product name : zucchini Bread which belongs to category Breads & cakes( main category) , Gluten free ( additional  Caegory) 

in product page i'm listing out all categories as shown in the ABOVE link
using the isotope i'm filtering out the products by category when  user clicks on breads zucchini Bread should display.. even when they click on Gluten Free also zucchini Bread shuld display .. but i'm getting only primary category  Breads & cakes .. but unable to fetch the additional categories .. researched shopaholic Documentation but unable to find the solution for that ...

**Comment by kharanenka** [comment]
I see that https://www.nuttynomnom.com/category/cakes-and-breads page has filter by categories. Did I understand you correctly, what do you want to see "zucchini Bread" when filtering by " Gluten Free" category?

I do not see sending ajax requests when applying a filter by category. How does filtering work on this page?

**Comment by kgangadhar** [comment]
you didn't understand it....

ok i just need the code to display the additional categories for each product that we upload from backend....

**Comment by kharanenka** [comment]
```
{% set obCategoryList = obProduct.additional_category %}
```

**Comment by kgangadhar** [comment]
need code for additional categories list for all products listing as below
https://www.nuttynomnom.com/all-products 

neither i'm additional category 

i'm accessing the category data like this 

{% set obaCategoryList = obProduct.additional_category %}
{% set obMCategoryList = obProduct.category %}
{% set arProductList = ProductList.make().active() %}  
{% set obCategoryList = CategoryList.make().active() %}

  <section class="topSingleBkg topPageBkg">
         <div class="item-content-bkg">
            <div class="item-img"  style="background-image:url({{'assets/images/slider/slider-1.jpg' | theme }});" ></div>
            <div class="inner-desc">
               <h1 class="post-title single-post-title">All Products </h1>
                <div class="post-desc"><h6 class=" text-white">{{ obCategory.description|raw }}</h6></div>
                <ul class="post-meta">
                  <li class="meta-date"><a href="{{ url('/')}}">Home</a>  </li>
                  <li class="meta-date"> / </li>
                  <li class="meta-date"><a href="{{ url('/Categories')}}">Products</a> </li>
                  <li class="meta-date"> / </li>
                  <li class="meta-date"> All </li>
                </ul>
            </div>
         </div>
      </section>

{% if obCategoryList.isNotEmpty() %}
    <div id="myBtnContainer" class="col-lg-10 col-12 mx-auto text-center">
    		<button class="col-md-2 col-3 view-more btn btn-primary mr-1 mt-2 mb-2 active" onclick="filterSelection('all')"> Show all</button>
        {% for obCategory in obCategoryList if obCategory.product_count >= 0 %}
           <button class="col-md-2 col-3 view-more btn btn-primary mr-1 mt-2 mb-2" onclick="filterSelection('{{obCategory.slug }}')"> {{ obCategory.name }}</button>
        {% endfor %}
   </div>
{% endif %}

  

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="gallery-4colgrid-content">
				<div class="menu-holder menu-3col-grid-image gallery-holder gallery-4col clearfix">
				{% for oProduct in arProductList %}  
				<div class="col-lg-12 col-12 filterDiv {{ oProduct.category.slug }} " >
					
					<div class="menu-post gallery-post " >
						<a href="{{ url('/products')}}/{{oProduct.slug}}"  title="{{ oProduct.name }} - {{ oProduct.category.slug }}">
							<div class="item-content-bkg gallery-bkg">
								<div class="gallery-img" style="background-image:url({{ oProduct.preview_image.path }});" title="{{ oProduct.category_id }} - {{ oProduct.name }} "></div>
								<div class="menu-post-desc"><h4>{{ oProduct.name }} </h4></div>
							</div>
						</a>
					</div>	
				</div>	
				{% endfor %}	
				</div>
			</div>
		</div>
	</div>
</div>

how do i get display additional categories , i'm unable to find the relation here

**Comment by kharanenka** [comment]
Do you mean this?
```
{% set obCategoryList = obProduct.additional_category %}
{% for obAdditionCategory in obCategoryList %}
    {{ obAdditionCategory.slug }}
{% endfor %}
```
