### ISSUE TITLE
Не работает поиск для языков, отличных от языка по-умолчанию [Search for Shopaholic]

### ISSUE THREAD

**Issue by vodolgiy** [oc-shopaholic/oc-shopaholic-plugin#289]
При поиске на дефолтном языке, метод search() из класса SearchHelper возвращает нужный айди из таблицы категорий, товаров и так далее, а вот при поиске на ином языке - возвращает айди из таблицы переводов (rainlab_translate_attributes), то есть айди перевода, а не айди нужного объекта.

Нужно заменить lists('id') на lists('model_id'), класс SearchHelper, строка 170

**Comment by kharanenka** [comment]
Fixed in version 1.2.1
