### ISSUE TITLE
How to filter categories by parent id?

### ISSUE THREAD

**Issue by EnzoBatista** [oc-shopaholic/oc-shopaholic-plugin#291]
I want to create a shop menu to show all parentcategories on the left side of the menu and when you put the mouse over the parent category you will see patern category photo, description, etc; and the list of it's childs categories on the right side of the menu.

Can you bring to me some example?

**Comment by EnzoBatista** [comment]
Hi @kharanenka 

I have seen the examples of categories, but I haven't found the correct way to get from the CategoryList collection a specific category with it's children

Can you give me an example, please?

**Comment by kharanenka** [comment]
You can get CategoryCollection with children categories from parent CategoryItem object

**Comment by kharanenka** [comment]
```
[CategoryData]
==

{% set obCategory = CategoryData.get(5) %}
{% set obChildrenCategoryList = obCategory.children %}
```

**Comment by EnzoBatista** [comment]
@kharanenka That's what i need, thank you!

I have one last question, I swear

If I do an update by ajax of a partial (using the handler 'onAjax') to update a variable that I passing into it for it's construction. How can I get this variable inside my partial?

`<div id="myDiv" class="col-7">
            {% partial 'header/category-list.htm' cat_id=null %}
          </div>`

`$.request('onAjax', {
        data: { cat_id: newId },
        update: { 'header/category-list': '#myDiv' }
      })`

**Comment by kharanenka** [comment]
You can use following example:
```{% set obCurrentCategory = CategoryData.get(input('cat_id')) %}```
