### ISSUE TITLE
How to update partial with a new variable value ?

### ISSUE THREAD

**Issue by EnzoBatista** [oc-shopaholic/oc-shopaholic-plugin#292]
I have this partial which recive a cat_id with a default value: null

<div id="myDiv" class="col-7">
      {% partial 'header/category-list.htm' cat_id=null %}
  </div>

Then i have capture the event onhover  and update the partial with the new cat_id value.

document.addEventListener("mouseover", function( event ) {
    event.preventDefault();
    if (!event.target.matches('.category-link')) return;
     let dataId = event.target.getAttribute('data-id');
      $.request('onAjax', {
        data: { cat_id: 1 },
        update: { 'header/category-list': '#myDiv' }
      })
  }, false);

Finally inside my partial how can i get the request cat_id from Ajax to update my partial content?

[CategoryData]
==
{% set obCategory = CategoryData.get(cat_id) %}
<h1>{{ obCategory.name }}</h1>

**Comment by kharanenka** [comment]
Hi! You can use following example:
```{% set obCategory = CategoryData.get(input('cat_id')) %}```
