### ISSUE TITLE
Error "Trait 'Kharanenka\Scope\ActiveField' not found" on october:up with v466

### ISSUE THREAD

**Issue by bcwaretx** [oc-shopaholic/oc-shopaholic-plugin#295]
When running october:up against OctoberCMS v1.0.466:

php artisan october:up

In Offer.php line 129:                                     
  Trait 'Kharanenka\Scope\ActiveField' not found  

Lovata.Shopaholic at 1.27.1

Reverting to 465 resolves issue.

**Comment by kharanenka** [comment]
Hi! It is bug of OctoberCMS (version 466).
We created issue and OctoberCSM core team have already fixed it. Fix will be added to 467 version.

**Comment by bcwaretx** [comment]
Got it! Will look for 467, or patch the changes from #5120: https://github.com/octobercms/october/issues/5110
