### ISSUE TITLE
How to get the discont_value from a obPromoBlock?

### ISSUE THREAD

**Issue by EnzoBatista** [oc-shopaholic/oc-shopaholic-plugin#298]
I want to show the promos with the discount value or total price, how can i do that?

**Comment by kharanenka** [comment]
Hi! What do you mean? Can you get some example?

**Comment by EnzoBatista** [comment]
I want to get the discount_value and price of a promoBlock which has discount asigned.
I've try the example in doc DiscountCollection.promoBlock($iPromoBlockID) but didn't work.

Then i've uninstall the plugin and when i try to reinstall the plugin doesn't appear in plugin search for install.

Please, can you help me?

**Comment by kharanenka** [comment]
Plugins doesn't have DiscountCollection component. You can create your custom component and add php code into your custom component:
```php
$obDiscountList = DiscountCollection::make()->promoBlock($iPromoBlockID);
```

**Comment by aarjona1991** [comment]
Hello, I am in the same situation. I want to capture the discount associated with a promotion and I can't find how !! According to the documentation [https://shopaholic.one/docs#/modules/promo-block/model/model] there is a relationship to know what the associated discount is, but it doesn't work for me. I have tried obPromoBlockFirst.discount and it returns nothing. What may be happening

**Comment by aarjona1991** [comment]
I've even looked inside the ** model ** PromoBlock and there is no relationship created for discounts, that's probably why ** PromoBlock.discounts ** didn't return anything

**Comment by kharanenka** [comment]
Variable **obPromoBlockFirst** is object of [**PromoBlockItem**](https://shopaholic.one/docs#/modules/promo-block/item/item) class. PromoBlockItem item class  and PromoBlock model class has different relations. PromoBlockItem class does not contain relation with discounts. You can get list of discounts with using code (it is example of php code, **not twig**):
```php
$obDiscountList = DiscountCollection::make()->promoBlock($iPromoBlockID);
```

**Comment by aarjona1991** [comment]
Great!!! it works for me!
