### ISSUE TITLE
PromoBlock's product collection it's not currently updateing

### ISSUE THREAD

**Issue by EnzoBatista** [oc-shopaholic/oc-shopaholic-plugin#308]
PromoBlock's product collection it's not currently updateing. If i delete  a product from a Promo in the admin it's ok, but it persist in collection on Twig!

**Comment by kharanenka** [comment]
Hi! Can you share your code from twig template?

**Comment by EnzoBatista** [comment]
@kharanenka  Hi there! 

Here is my Twig code:

`{% set obPromoBlockList = PromoBlockList.make().active() %}
{% set obPromoBlockFirst = PromoBlockList.make().active() | first %}`

`{% for obPromo in obPromoBlockFirst.product %}
            {% partial 'catalog/product/product-item' obPromo=obPromo %}
          {% endfor %}`

If I delete a product from the promo it still in obPromoBlockFirst.product wich is the collection of products of obPromo.

**Comment by kharanenka** [comment]
I should to check cache flush

**Comment by EnzoBatista** [comment]
@kharanenka Let me know if you have news! Thank you

**Comment by kharanenka** [comment]
Ok

**Comment by EnzoBatista** [comment]
@aarjona1991 That's what I told you...

**Comment by wobqqq** [comment]
@EnzoBatista 
You need to add an active() method for the product collection
Example:
{% for obPromo in obPromoBlockFirst.product.active() %}
{% partial 'catalog/product/product-item' obPromo=obPromo %}
{% endfor %}
