### ISSUE TITLE
Coupon SHOPA10K not woking any more..

### ISSUE THREAD

**Issue by Dymskiy** [oc-shopaholic/oc-shopaholic-plugin#310]
Tried to buy Sneakers E-Commerce Theme for Shopaholic with coupon SHOPA10K shown on Details page but "This coupon cannot be used"... Without coupon theme is too expensive for me.. :'( Remove info about discount at least..

**Comment by kharanenka** [comment]
Hi! Coupon was valid from 8 to 14 June

**Comment by lautsevich** [comment]
@Dymskiy, hi!

Thx for paying attention to the outdated information. It's fixed now.

If you still need this theme, please drop an email to shopaholic@shopaholic.one and we'll discuss it.
