### ISSUE TITLE
i cant see the partials on october cms 

### ISSUE THREAD

**Issue by frasjaf** [oc-shopaholic/oc-shopaholic-plugin#318]
hi i try to edit partials but i not see it in october cms

**Comment by lautsevich** [comment]
@frasjaf, are you talking about official themes (Sneakers or Bootstrap)?

**Comment by kharanenka** [comment]
Hi! OctoberCMS only supports displaying partials at top nesting level. We put partials in theme in subdirectories and grouping partials by logic unions, which makes it easy to find files and navigate list of partials during development.
