### ISSUE TITLE
Feature Request: Duplicate offer item

### ISSUE THREAD

**Issue by johnnywo** [oc-shopaholic/oc-shopaholic-plugin#323]
Hi, it would be really nice if I just could clone an existing offer item (and apply small modifications afterwards). Instead of running the process of creating a new one each time. 

Thank you,
Emil

**Comment by lautsevich** [comment]
@johnnywo, such a good idea. We'll develop it some. Feel free to develop it by yourself and send a PR.

**Comment by johnnywo** [comment]
@lautsevich thank you - if I feel able to do that I will!
