### ISSUE TITLE
Feature Request: Attach- / Detach offer item from product

### ISSUE THREAD

**Issue by johnnywo** [oc-shopaholic/oc-shopaholic-plugin#324]
Hi! It would be really nice if I would have the possibility to attach / detach offer item from product. (Instead of deleting offer item and creating a new one)

Thank you,
Emil

**Comment by lautsevich** [comment]
@johnnywo, hi. You can activate/deactivate offers.

![image](https://user-images.githubusercontent.com/196445/96610835-c02e7880-1304-11eb-827d-f031c4c95bab.png)

Is this what are you looking for?

**Comment by johnnywo** [comment]
@lautsevich thanks anyway - after rethinking this I think it is not possible what I suggested (because this is a 1:many relationship and feature what I thought would be many:many relationship between offer and product)
