### ISSUE TITLE
Cant load css styles after compiled npm run dev

### ISSUE THREAD

**Issue by jahoora** [oc-shopaholic/oc-shopaholic-plugin#334]
Hello, please help me
I have problem, after compiled npm run dev not load css style on index page
![Снимок экрана 2021-01-19 в 02 12 50](https://user-images.githubusercontent.com/51854729/104970299-01b1eb00-59fc-11eb-85a8-cb363a7bf7ec.png)
![Снимок экрана 2021-01-19 в 02 13 17](https://user-images.githubusercontent.com/51854729/104970303-02e31800-59fc-11eb-9697-d88113caf075.png)

**Comment by kharanenka** [comment]
Hi! Do you have compiled files? What local domain do you use?

**Comment by jahoora** [comment]
Yeah, in attach files
My domen is: http://localhost:8888/dps/
[Новая папка 2.zip](https://github.com/oc-shopaholic/oc-shopaholic-plugin/files/5836106/2.zip)

**Comment by kharanenka** [comment]
Please fix path to css/js files in tempalte file. Template has absolute path. For example: /themes/***/assets/css/common.css
If you uses folder (dps) for your root folder, then you should fix absolute path and add "dps" folder to assets path.

**Comment by jahoora** [comment]
Let me know please what a "template file" you mean?

**Comment by kharanenka** [comment]
I mean "layouts" files

**Comment by jahoora** [comment]
This is original code in main layout :
`<?php
function onInit()
{
    $this['path_css'] = mix('css/common.css', 'themes/'.\Cms\Classes\Theme::getActiveTheme()->getDirName().'/assets');
    $this['path_js'] = mix('js/common.js', 'themes/'.\Cms\Classes\Theme::getActiveTheme()->getDirName().'/assets');
    $this['cart_is_available'] = false;

    /**
     * Check if Cart component has been registered and autoload it
     **/

    $obManager = \Cms\Classes\ComponentManager::instance();
    if ($obManager->hasComponent('Lovata\OrdersShopaholic\Components\Cart')) {
        $this['cart_is_available'] = true;
        $this->addComponent('Lovata\OrdersShopaholic\Components\Cart', 'Cart', []);
    }

    if ($obManager->hasComponent('Lovata\MightySeo\Components\SeoToolbox')) {
        $this['seo_toolbox_is_available'] = true;
        $this->addComponent('Lovata\MightySeo\Components\SeoToolbox', 'SeoToolbox', []);
    }
}`

Here for example i add "dps" for path_css

`<?php
function onInit()
{
    $this['path_css'] = mix('css/common.css', 'dps/themes/'.\Cms\Classes\Theme::getActiveTheme()->getDirName().'/assets');
    $this['path_js'] = mix('js/common.js', 'themes/'.\Cms\Classes\Theme::getActiveTheme()->getDirName().'/assets');
    $this['cart_is_available'] = false;

    /**
     * Check if Cart component has been registered and autoload it
     **/

    $obManager = \Cms\Classes\ComponentManager::instance();
    if ($obManager->hasComponent('Lovata\OrdersShopaholic\Components\Cart')) {
        $this['cart_is_available'] = true;
        $this->addComponent('Lovata\OrdersShopaholic\Components\Cart', 'Cart', []);
    }

    if ($obManager->hasComponent('Lovata\MightySeo\Components\SeoToolbox')) {
        $this['seo_toolbox_is_available'] = true;
        $this->addComponent('Lovata\MightySeo\Components\SeoToolbox', 'SeoToolbox', []);
    }
}
?>`

but after change i have exception
![Снимок экрана 2021-01-20 в 23 56 18](https://user-images.githubusercontent.com/51854729/105233641-2da7aa80-5b7b-11eb-95ea-7797365ed48b.png)
