### ISSUE TITLE
increase price of offer on cart adding with some property

### ISSUE THREAD

**Issue by Vadimlj** [oc-shopaholic/oc-shopaholic-plugin#335]
i want to have two property that have editing price in theme options
and i don't want to create for all products offers dependence of that property
how can i add my 10$ to every offer that added with my property to cart

**Comment by Vadimlj** [comment]
Hi, are there any ideas on this issue?

**Comment by kharanenka** [comment]
Hi, You can use "Increase price mechanism". It is promo mechanism with **$bIncrease** flag == true.
It will provide an opportunity to increase the price of the cart position.

**Comment by Vadimlj** [comment]
Please could you show some example without creating conditions in Increase price mechanism, and how should i pass data to json onAdd method i'm trying add some product like this

let data = {
  'cart': [
    {'offer_id': 32, 'quantity': 4, 'property': {'another_offers': '3, 4'}}, here i will add prices of 3 and 4 offer id
    {'offer_id': 32, 'quantity': 1, 'property': {'another_offers': '3'}} here i will add price of 3 offer id
    {'offer_id': 32, 'quantity': 1}
  ],
};

**Comment by lautsevich** [comment]
@Vadimlj, let me invite you to community chats:
- https://t.me/oc_shopaholic
- https://discord.gg/zvfU26wB

IMO, this way we'll help you daster. Besides, you can speak Russian there. ;)

**Comment by Vadimlj** [comment]
Thank you, I'm already there, but if is it possible, i will waiting for your answer here, maybe some one else will looking for solution

**Comment by lautsevich** [comment]
As you wish.

**Comment by Vadimlj** [comment]
@kharanenka спасибо 
`
Event::listen(\Lovata\OrdersShopaholic\Classes\PromoMechanism\CartPromoMechanismProcessor::EVENT_GET_MECHANISM_LIST, function($obPromoProcessor){
                $cart = CartProcessor::instance()->get();
                foreach($cart as $pos => $cartPosition){
                        if(isset($cartPosition->property) && $cartPosition->property['another_offers'] ) {
                                $addPrice = 0;
                                $offers = explode(',', $cartPosition->property['another_offers']);
                                
                                foreach($offers as $offer){
                                        $addPrice += (int) OfferItem::make($offer)->price;
                                }
                                
                                $obMechanism = new WithoutConditionDiscountPosition(0, $addPrice, 'fixed', 0, ['position' => $pos], true);
                                $obMechanism->setCheckPositionCallback(function($obPosition) use ($pos) {
                                        if($obPosition->id == $pos) return true;
                                });
                                $obPromoProcessor->addMechanism($obMechanism);
                        }
                }
        });
`

как то так все работает замечательно
