### ISSUE TITLE
How to list the properties grouped with property set name?

### ISSUE THREAD

**Issue by quildcrest** [oc-shopaholic/oc-shopaholic-plugin#343]
I want to list the properties like this:
Propertyset1:
  Property 1: value
  Property 2: value
Propertyset2:
  Property 3: value
  Property 4: value

Thanks.

**Comment by quildcrest** [comment]
I found it in the doc. Thanks.

**Comment by gvanto** [comment]
@quildcrest would be great if you shared the link to the docs where you found it (helps others).
