### ISSUE TITLE
Product URL not working

### ISSUE THREAD

**Issue by gvanto** [oc-shopaholic/oc-shopaholic-plugin#384]
I have installed Shopaholic plugin and entered a product, but cannot seem to access the product page (I've tried /catalog/{catCode}/{productUrl}, (and all kinds of variations of this) etc trying to compare with the demo site's URLs (my url is following same structure).

Product info:
![image](https://user-images.githubusercontent.com/8372918/129470992-329ba6e2-d401-47e9-908c-a0a37d81b809.png)

Category info (do I *need* to use a category?)
![image](https://user-images.githubusercontent.com/8372918/129470999-779adf2b-61c8-415d-ac4e-4ec9456f3f2e.png)

Product list:
![image](https://user-images.githubusercontent.com/8372918/129471022-c4fe5355-daa3-40fe-a214-5a4a06d73b7e.png)

When I access {mysite.test}/catalog/forex/blademiner-licence error is "Page not found", but I don't know if it's because product misconfigured or if I need to be using another theme (I am using my own custom theme, nothing added so far to cater for products, but does it need it?)

Can't seem to find any basic documentation on this? (the [official docs](https://shopaholic.one/doc) seem more like a developer specification than a user guide to be honest)

But overall I am excited to use this plugin seems promising!

**Comment by wobqqq** [comment]
@gvanto 

1. You need to create a product page with this URL catalog/:category/:product 
2. Add the ProductPage CategoryPage components to this page. and copy the component settings from the screenshot.

![image](https://user-images.githubusercontent.com/31685258/129859116-82183524-6d50-4505-8c33-081cf1976afa.png)

![image](https://user-images.githubusercontent.com/31685258/129859189-e95ca783-80dc-4d98-8a8f-e48577e91d54.png)

**Comment by gvanto** [comment]
Ok thanks a lot. I think would be great if the docs can include your answer (I had to find it in forum threads), as this really is the basics...

**Comment by gvanto** [comment]
How do I set a price on a product? (also not in docs here: https://octobercms.com/plugin/lovata-shopaholic#documentation)

**Comment by wobqqq** [comment]
@gvanto Do you mean it? https://shopaholic.one/docs#/modules/offer/home?id=backend

**Comment by gvanto** [comment]
Thanks @wobqqq
