### ISSUE TITLE
Mighty SEO CMS version compatibility

### ISSUE THREAD

**Issue by robwent** [oc-shopaholic/oc-shopaholic-plugin#401]
Apologies if this is the wrong place to ask.

I'm looking at the MightySEO plugin and was wondering what versions of the CMS it supports:
https://octobercms.com/plugin/lovata-mightyseo

After getting errors with some other plugins, I found that it was due to them requiring V2, but it seems our site is built on V1.

Also, does it support category pages as well as products and do you have any plans to add opengraph tags or product schema data?

Thanks!

**Comment by lautsevich** [comment]
Hi @robwent!

The plugin supports both versions. At least, we don't know any compatibility issues with version 2. And, yes, the plugin has the full support of the Shopaholic catalog.

**Comment by robwent** [comment]
Thanks!

**Comment by robwent** [comment]
Is there something missing from the docs about getting this to work on cms pages/pages?

It's working fine for products but there's nothing happening with pages and I'm not sure if I need to add anything to the app.php config file to get the options to show up.
I've added the component to the page but nothing changes.

**Comment by lautsevich** [comment]
@robwent nope, it should work if you followed the manual. @kharanenka, any ideas?

**Comment by robwent** [comment]
The only manual I could find was the documentation tab on the plugin page here: https://octobercms.com/plugin/lovata-mightyseo
The product support link comes to this repo.

In a catalogue item I get an SEO tab like this:
![cat](https://user-images.githubusercontent.com/411678/151359506-1f952475-46a5-445a-a306-9ad32b03d99e.png)

In pages, I just have the default meta tab.
![page](https://user-images.githubusercontent.com/411678/151359726-80d60815-ca0b-4111-8c4f-c46630928793.png)

And then in CMS > pages it's the same
![cms-meta](https://user-images.githubusercontent.com/411678/151359924-cd1932c0-ea86-4be9-add3-b341e2758ae2.png)


I'm not sure exactly where to see the October version in the admin area, but in the composer.lock file I see october/cms showing as v1.0.471

**Comment by lautsevich** [comment]
There's no separate tab for this. Please, find the `SEO` item in the global navigation in the admin dashboard.
 
![image](https://user-images.githubusercontent.com/196445/151669243-afb90d14-ce12-401f-8940-05a862bdd940.png)

**Comment by robwent** [comment]
Ah, it all becomes clear. Thanks.

It would be good to add a note about this to the plugin page.

**Comment by lautsevich** [comment]
@robwent UX improvement is on our roadmap! ;)
