### ISSUE TITLE
Trying to add a Property set to category

### ISSUE THREAD

**Issue by ostlancer** [oc-shopaholic/oc-shopaholic-plugin#404]
Trying to add a Property set to category:
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inherit_property_set' in 'field list' (SQL: update `lovata_shopaholic_categories` set `code` = , `preview_text` = , `description` = , `inherit_property_set` = 0, `lovata_shopaholic_categories`.`updated_at` = 2022-02-28 09:25:40 where `id` = 1)" on line 669 of /var/www/site.ru/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by kharanenka** [comment]
Hello! Try to reinstall Properties for shopaholic plugin, because inherit_property_set field added via migration in v1.8.0
