### ISSUE TITLE
"A node cannot be moved to a descendant of itself."

### ISSUE THREAD

**Issue by buzmate** [oc-shopaholic/oc-shopaholic-plugin#407]
When I try to create a category without a parent category I get the following error.

"A node cannot be moved to a descendant of itself." on line 1028 of /home7/gvoucher/public_html/vendor/october/rain/src/Database/Traits/NestedTree.php

This happens on version 1.30.3 and 1.30.4. It works fine on version 1.30.1. I didn't check version 1.30.2

**Comment by kharanenka** [comment]
Hello! We can't reproduce this bug, because last versions of Shoapholic plugins doesn't support v1 and v2 of OctoberCMS
