### ISSUE TITLE
Product properties are not displayed after caching by the site on build 476 and the latest Properties for Shopaholic update

### ISSUE THREAD

**Issue by twofed1** [oc-shopaholic/oc-shopaholic-plugin#409]
Hello!
I've updated OctoberCMS and all the plugins to the current build (476), after this occurred the following problem - if I reset the site cache, the product page properties are displayed correctly. After refreshing the page and until the next reset of the cache properties are not displayed.

**Comment by kharanenka** [comment]
Hello! We can't reproduce this bug, because last versions of Shoapholic plugins doesn't support v1 and v2 of OctoberCMS
