### ISSUE TITLE
Class "Twig_Extension_StringLoader" not found

### ISSUE THREAD

**Issue by potioncodes** [oc-shopaholic/oc-shopaholic-plugin#410]
I know that this extension is part of the Twig Extension plugin that you are using in this Theme. Have you ever had this error or know how to fix this?

**Comment by kharanenka** [comment]
Hello! Please inspect documentation of [Twig extensions](https://octobercms.com/plugin/vojtasvoboda-twigextensions) plugin (changelog and upgrade tabs)
