### ISSUE TITLE
Get promo data in cart model

### ISSUE THREAD

**Issue by fmalizia21** [oc-shopaholic/oc-shopaholic-plugin#411]
Hello,

how can I access the active promo  in the cart model?
![Schermata 2022-07-20 alle 18 07 16](https://user-images.githubusercontent.com/18569595/180030263-ce7e3d49-b1e3-4e1e-b41f-38775aad4dce.png)

I can access the coupons, but there isn't a relation for the promo. 
Another question, where is stored the promo active in the cart?

Thank you

**Comment by igor-tv** [comment]
Hello

The Cart model has no relationship with PromoMechanism. Promo mechanisms are stored in the $obPromoProcessor protected property of CartProcessor.

On the frontend, they usually check the discount_price_value of the cart item or the active shipping type to display the old price and the price including all discounts.

The Cart component also has a getDiscountTotalPriceValue() method, which returns the total cost of the order including all discounts and promo mechanisms.
