### ISSUE TITLE
How can I filter the panel by category type?

### ISSUE THREAD

**Issue by ANZ504** [oc-shopaholic/oc-shopaholic-plugin#412]
What I want to achieve is to filter the products by category on the catalog page.

And in the documentation there is nothing related to filtering by category.

Thanks!

**Comment by igor-tv** [comment]
There is a `category($iCategoryID, [$bWithChildren = false])` method that can be applied to the ProductCollection.
https://shopaholic.one/docs#/modules/product/collection/collection?id=categoryicategoryid-bwithchildren-false

**Comment by ANZ504** [comment]
Thx
