### ISSUE TITLE
How can i disable a colorpicker property for a product?

### ISSUE THREAD

**Issue by gcsomesz** [oc-shopaholic/oc-shopaholic-plugin#414]
Hello, I have a product with five color property. One product is no longer available in the requested color. How can I disable one color picker property for this product?

Thanks!

**Comment by igor-tv** [comment]
Please provide more details about your task. Do you mean a predefined set of colors in the colorpicker type property on the backend, or are you talking about a product list filter on the frontend.

<img width="765" alt="Снимок экрана 2022-08-18 в 15 48 37" src="https://user-images.githubusercontent.com/6777469/185398587-dd2d4346-1a1f-4f3b-b0f4-0791f9cff7f2.png">

**Comment by igor-tv** [comment]
You can extend the Product model if the product model matches the desired product id or code, and remove the color property field by its code, and then add a field with the same code, and set only the desired colors in the repeater color preset.

This question does not apply to Shopaholic. This is about OctoberCMS backend forms extension. https://docs.octobercms.com/2.x/plugin/extending.html#extending-backend-forms

**Comment by gcsomesz** [comment]
Sorry, but maybe this is a missunderstanding. I could set 1 or 4 or 3 or whatever color option for a product, but just can't turn off the color when a product with a specified variation is not avaliable for a few week?
