### ISSUE TITLE
Номер заказа в теме письма

### ISSUE THREAD

**Issue by EsekhinSA** [oc-shopaholic/oc-shopaholic-plugin#422]
Здравствуйте! Очень не хватает номера заказа в теме письма. Без него менеджеры путаются в потоке писем. Это возможно исправить?

<img width="1792" alt="Снимок экрана 2022-11-14 в 19 13 39" src="https://user-images.githubusercontent.com/38294171/201709783-69e3558a-c73a-4d2d-84bd-96db1611d864.png">

**Comment by kharanenka** [comment]
Добрый день. Попробуйте добавить в Subject письма переменную {{ order_number }} 
Если это не сработает, то для вывода номера заказа в теме письма нужно будет делать доработки

**Comment by EsekhinSA** [comment]
Благодарю за ответ! Работает
