### ISSUE TITLE
There's no Properties tab in Catalog Configuration-Basic Settings

### ISSUE THREAD

**Issue by euge001** [oc-shopaholic/oc-shopaholic-plugin#433]
There's no Properties tab in Catalog Configuration-Basic Settings

mine:
![image](https://github.com/oc-shopaholic/oc-shopaholic-plugin/assets/12379144/4e176114-6b63-4c12-8c47-b6359120f597)
(...and css here also looks weird, I've tried diferent page zooming, 100% is on printscreen)

yours:
![image](https://github.com/oc-shopaholic/oc-shopaholic-plugin/assets/12379144/336ebf90-e067-4150-b9dd-30e53fbf3309)

**Comment by kharanenka** [comment]
Tab pannel is too long. Please scroll tabs from right to left via mouse
