### ISSUE TITLE
The detailed information a.k.a Wiki Page in Github about the Shopaholic plugin is gone OR the links here are not working as it seems. 

### ISSUE THREAD

**Issue by newclb** [oc-shopaholic/oc-shopaholic-plugin#435]
Please provide us links to the detailed information how to use the **Shopaholic** plugin, because it's **impossible to understand** without working examples...also the DEMO online shop page is not working AND your **Bootstrap Demo Theme** too...

**Comment by kharanenka** [comment]
Hi! Did you inspect [docs](https://shopaholic.one/docs#/) ?
