### ISSUE TITLE
Money were successfully taken but no product delivered. 

### ISSUE THREAD

**Issue by euge001** [oc-shopaholic/oc-shopaholic-plugin#437]
![image](https://github.com/oc-shopaholic/oc-shopaholic-plugin/assets/12379144/e2a0ae7f-a2a6-449b-bdaf-ef211511f943)

**Comment by euge001** [comment]
I get this message when trying to sync my Project and Theme I paid $99 for. Please provide some way I can get files please ASAP. I don't like scam, sorry.

**Comment by kharanenka** [comment]
Hello, i think that it is problem of OctoberCMS, because marketplace store full copy of plugins and themes.

**Comment by euge001** [comment]
where I can find a tutorial for that?

**Comment by lautsevich** [comment]
@euge001, I would suggest you study the basics of October CMS. Start with official documentation [here](https://docs.octobercms.com/). The answer to your question is in one [step](https://docs.octobercms.com/3.x/resources/installing-packages.html) from the index page of the documentation.
