### ISSUE TITLE
Command "shopaholic:generate. Did you mean one of these?  

### ISSUE THREAD

**Issue by euge001** [oc-shopaholic/oc-shopaholic-plugin#439]
![image](https://github.com/oc-shopaholic/oc-shopaholic-plugin/assets/12379144/3eceaa9b-9616-46f0-949f-b96916111e92)

**Comment by kharanenka** [comment]
Hello, please install [Fake data for Shopaholic](https://octobercms.com/plugin/lovata-fakedatashopaholic) plugin. Plugin contains two commnads:
```
php artisan shopaholic:generate.fake.data
```
```
php artisan shopaholic:generate.theme.fake.data
```
