### ISSUE TITLE
Sort cart by products popularity

### ISSUE THREAD

**Issue by YanMetelitsa** [oc-shopaholic/oc-shopaholic-plugin#443]
Hi! Is it possible to sort cart positions by products popularity?

Thanks!

**Comment by kharanenka** [comment]
Hi! We don't have some logic. But you can extend CartPositionCollection class (link on [docs](https://shopaholic.one/docs#/modules/cart-position/extending/extending?id=add-custom-filter)) and add your custom method.

For example:

```php
$obCartPositionList->addDynamicMethod('sorting', function () use ($obCartPositionList) {            
    $arResultIDList = (array) ... put custom logic and return array with sorted cart positions

    return $obCartPositionList->applySorting($arResultIDList);
});
```
