### ISSUE TITLE
Class "RainLab\User\Facades\Auth" not found

### ISSUE THREAD

**Issue by get-web** [oc-shopaholic/oc-shopaholic-plugin#446]
Installed Toolbox, Shopaholic, Brainlab.User
I'm going to /backend/lovata/shopaholic/products
I get the error: Class "RainLab\User\Facades\Auth" not found

OctoberCMS v3.7.4

**Comment by kharanenka** [comment]
Hello, fixed in Lovata.Toolbox plugin v2.2.0
