### ISSUE TITLE
Question about the coming store plugin

### ISSUE THREAD

**Issue by ghost** [oc-shopaholic/oc-shopaholic-plugin#79]
Hello,

I'm really interested by ecommerce with october cms and your plugin seems to be one of the most developped initiative.

By reading your plugin description, it seems you plan to add "stores" features to shopaholic.

I wonder if it's future store plugin would allow to create marketplaces. By marketplace, I mean the way to have different stores on the shop, with their own list of products, and when a customer buy some products on different stores, dispatch payments between all sellers in proportion of their sales in that order.

Cause I would be really interested by this feature for an upcoming project.

Thank you for your answer.

Best regards,

Alex

**Comment by kharanenka** [comment]
Hi!
In the "Stores" plugin we think to add the ability to create stores and attach offers to stores. This will show the offers that are now in the selected store.
For marketplace we need to add Vendor model.
This is a more complex logic for the site. This option is likely to be made as a separate plugin "Marketplace"

**Comment by Alex360hd** [comment]
Hi,

Thank you for the answer.

Best regards,

Alex

**Comment by lautsevich** [comment]
Hi @Alex360hd,

Due to a lot of requests for the multi-vendor functionality for Shopaholic we just opened a Github issue #176 for gathering the requirements for this. Don't hesitate to provide your thoughts and experience it this domain.
